### ISSUE TITLE
single box deployment k8s step issue

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1967] opened 2019-01-02 09:28 UTC
**Organization Name**: 

Follow single box deploy. only type 1 node ip in quick-start.
But deploy meet hanging issue. [issue1]
https://github.com/Microsoft/pai/blob/master/docs/pai-management/doc/single-box.md

[issue2] currently doc should tell user how to config the quick start

**Short summary about the issue/question**:
single box deploy, but hanging on this log:

![image](https://user-images.githubusercontent.com/5576848/50586212-81bb9580-0eb3-11e9-85a2-c773392c493c.png)

**Brief what process you are following**: 
follow this 
https://github.com/Microsoft/pai/blob/master/docs/pai-management/doc/single-box.md
generate configuration step: type 1 ip address.

**How to reproduce it**: 

**OpenPAI Environment**:
- OpenPAI version: v0.8.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by ydye** [comment] 2019-01-03 06:51
If you deploy OpenPAI v0.8.2. Please follow this doc: https://github.com/Microsoft/pai/blob/pai-0.8.y/docs/pai-management/doc/cluster-bootup.md#singlebox

**Comment by YanjieGao** [comment] 2019-01-03 06:53
my branch is checkout from yesterday's master, not v0.8.2

**Comment by ydye** [comment] 2019-01-03 06:55
https://github.com/Microsoft/pai/blob/master/docs/pai-management/doc/single-box.md#c-step-2 Option A will guide you to write template.

**Comment by ydye** [comment] 2019-01-03 06:55
For the first issue, the detailed information should be provided

**Comment by ydye** [comment] 2019-01-03 06:56
1) to the target node
2) docker ps -a
3) docker logs kubelet.

**Comment by ydye** [comment] 2019-01-03 06:57
And another things you should do is determine whether the node is deployed pai before. If yes, please clean the node then deploy.

**Comment by YanjieGao** [comment] 2019-01-03 06:57
yes deployed before and i clean use k8s-clean and service delete

**Comment by YanjieGao** [comment] 2019-01-03 06:59
yes i follow this doc 
https://github.com/Microsoft/pai/blob/master/docs/pai-management/doc/single-box.md#c-step-2 and only type master ip. in this doc we don't tell user should type 1 ip address which should be note or customized tell user.

**Comment by YanjieGao** [comment] 2019-01-03 07:03
kubelet info, seems related to disk? what is pai's k8s disk threshold? :
![image](https://user-images.githubusercontent.com/5576848/50626329-7fffd980-0f68-11e9-8169-dc46b55a427d.png)

server disk usage:
![image](https://user-images.githubusercontent.com/5576848/50626352-a32a8900-0f68-11e9-8a30-ad698bd354bd.png)

![image](https://user-images.githubusercontent.com/5576848/50626336-8b530500-0f68-11e9-9621-b43ea4db805c.png)

**Comment by ydye** [comment] 2019-01-03 07:07
Do you deploy openpai with single-box? For the issue, i found kubectl try to connect x.x.x.131. And in another place, i found the master node address is x.x.x.133

**Comment by YanjieGao** [comment] 2019-01-03 07:08
I also try at node on 131
issue seems related with etcd:
![image](https://user-images.githubusercontent.com/5576848/50626469-690db700-0f69-11e9-9bad-2924caea3959.png)

disk is free:
![image](https://user-images.githubusercontent.com/5576848/50626478-7b87f080-0f69-11e9-8252-0e4677dd20a0.png)

**Comment by YanjieGao** [comment] 2019-01-03 07:09
yes single box deploy: i tried on 133 and 131

**Comment by YanjieGao** [comment] 2019-01-03 07:43
works Note:

For previous deployed pai install single box
1 force clean
sudo python paictl.py cluster k8s-clean  -p ~/yanjie/e2e_test_refine/pai-config-single/ -f

2 sudo install k8s

 sudo python paictl.py cluster k8s-bootup  -p ~/yanjie/e2e_test_refine/pai-config-single/

**Comment by ydye** [comment] 2019-01-03 11:14
The issue is solved, I will closed it.

**Closed by ydye** 2019-01-03 11:14 UTC
