### ISSUE TITLE
STDOUT/STDERR only get "Failed to fetch"

### ISSUE THREAD

**Issue by ReyRen** [microsoft/pai#5159] opened 2020-12-10 11:38 UTC
**Organization Name**:

**Short summary about the issue/question**:
The `stdout` and `stderr` show "Failed to fetch" when I use  my own image to do the training test. I'm sure the command I specified in .yaml would get tons of logs to stdout, however, it would stuck at "USER COMMAND START" when I use `kubectl logs -f  podID ` to check the stdout logs and "USER COMMAND END" after a while. And the openPAI stdout/stderr get "Failed to fetch"

submit a job

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
v1.3.0
- Cloud provider or hardware configuration:
local env
- OS (e.g. from /etc/os-release):
Ubuntu 18.04
- Kernel (e.g. `uname -a`):
Linux node4 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
nvidia GPU
- Others:
yaml file:
```
protocolVersion: 2
name: hello-world-job10
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'whoami179/tensorflow-tb-test-data:test'
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 5
      memoryMB: 15253
    commands:
      - cd /root/hymenoptera
      - python train.py
defaults:
  virtualCluster: default
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
  hivedScheduler:
    taskRoles:
      taskrole:
        skuNum: 1
        skuType: DT
```

**Anything else we need to know**:
Thanks in advance

**Comment by fanyangCS** [comment] 2020-12-10 12:16
maybe you can ssh to the job container and run the commands to see the response.

**Comment by ReyRen** [comment] 2020-12-10 12:28
> maybe you can ssh to the job container and run the commands to see the response.

@fanyangCS Thanks for your respond. Tons of logs output to STDOUT in the job container even I use ssh to the job container.

**Comment by ReyRen** [comment] 2020-12-10 12:33
I suspect the init container played tricky in it :) maybe redirect the file describe?

**Comment by ReyRen** [comment] 2020-12-10 12:37
The job would finish successful in reasonable training span. But only output "USER COMMAND START""USER COMMAND END" checked with `kubectl logs`

**Comment by Binyang2014** [comment] 2020-12-11 03:17
@ReyRen, can you check this status of `log-manager`. You can use ` kubectl describe ds log-manager-ds ` to check if log-manager is ready.
And please check the related pod is up and ready to serve request.

**Comment by ReyRen** [comment] 2020-12-11 03:27
@Binyang2014 hmmm, I upgrade to the latest release version (v1.4.0), and get those logs successful. Thanks anyway. :)
This issue can be closed.

**Comment by Binyang2014** [comment] 2020-12-11 04:21
Thanks, I found this error is caused by:
```
jobDetail.80328e05dc8c87cd4606.js:1 Mixed Content: 
The page at 'https://xxx/job-detail.html?username=name&jobName=hello-world-job1' was loaded over HTTPS, 
but requested an insecure resource 'http://xxx:9103/log-manager/tail/name/1825b686aac8c216c9c110c199267521/taskrole/a3ba2256-3b60-11eb-830b-000d3ab25bb6/user.pai.stdout'. 
This request has been blocked; the content must be served over HTTPS.
```
This may due to the browser update. FYI: https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

We changed the log API in v1.4.0. So this issue should be fixed. Thanks for report

**Comment by Binyang2014** [comment] 2020-12-11 04:23
close this. @debuggy @yiyione please aware this behavior

**Closed by Binyang2014** 2020-12-11 04:23 UTC
