### ISSUE TITLE
[job status]   Task status shows running, but no resources are allocated. 

### ISSUE THREAD

**Issue by hirolsj** [Microsoft/pai#2022] opened 2019-01-17 03:21 UTC

**Comment by mzmssg** [comment] 2019-01-17 03:49
It need launcher expose this info?

**Comment by hirolsj** [comment] 2019-01-17 06:44
I think webportal have to make some change。Job status(running) should be scheduling when no cantainer info(container name and ip) returned . And job status should be running when container info returned.

**Comment by hirolsj** [comment] 2019-01-17 06:58
It is a better idea if launcher expose this info.But there would be too much work to do .

**Comment by hirolsj** [comment] 2019-01-18 02:59
Yes，it need launcher expose this info。

**Comment by mzmssg** [comment] 2019-01-18 09:40
@yqwang-ms @Gerhut , how do you think, is it necessary?

**Comment by yqwang-ms** [comment] 2019-01-18 10:37
It is by design and aligned with YARN. App running means AM container is running, it is not nessary that User's task container is also running.

**Comment by scarlett2018** [comment] 2019-01-19 14:53
I got the similar asks from users as well. Let's find a time next week and discuss what's the best we can do @yqwang-ms @mzmssg @Gerhut

**Comment by mzmssg** [comment] 2019-01-22 02:41
@yqwang-ms 
I think launcher is an abstract layer between user and bottem platform(k8s or YARN), so seems it should have an isolated, unified status. 
For this case, I think yarn-launcher status would be `running`, but k8s-launcher would be  `waiting`? If so, is it too confusing?

**Comment by yqwang-ms** [comment] 2019-01-22 02:54
No, both yarn-launcher and k8s-launcher are running as soon as the whole job attempt object is created, regardless of whether the job attempt has running tasks.
For example, if launcher runs a servce with 3 instances initially, and then, we lost all these instances and restarting, so should we change the whole job from running to waiting during this period?
Another example is, TF require all instances running then the whole job is started to run, only run one instance should not mark the whole job as running.
So, I think the whole job running status depends on each job scenario, and it does not impact the job state machine, it just tell user the more user friendly info, so launcher just make it running as soon as the whole job attempt object is created for simplicity. And PAI RestServer or other top layer components can revise these status to show more user friendly info.

**Comment by fanyangCS** [comment] 2019-02-01 04:32
close this issue and track in #824 .

**Comment by yqwang-ms** [comment] 2019-02-12 09:29
We plan to revise it now, see #2135

**Comment by yqwang-ms** [comment] 2019-02-12 12:06
Solved by #2135

**Closed by yqwang-ms** 2019-02-12 12:06 UTC
Labels: C-BITA-USTC, ResourceAllocation, enhancement, high priority, raised by customer
