### ISSUE TITLE
about: PAI Homepage visiting Intranet IP. 

### ISSUE THREAD

**Issue by boozyguo** [Microsoft/pai#1136] opened 2018-08-23 16:49 UTC
hello, 
There is a problem about public IP and intranet IP.
I have deploy PAI in a intranet server which has a intranet ip 192.168.1.191.
Then the router maps the public ip 114.250.x.x to the server.
So people could through public ip 114.250.x.x  visit 192.168.1.191. 
But, the PAI homepage (Platform for AI) can not display graph and tables, because the webpage including some request for 192.168.1.191, for example:

GET http://192.168.1.191/grafana/public/build/grafana.dark.css?v4.6.3 net::ERR_CONNECTION_TIMED_OUT
pai_clusterview:89 GET http://192.168.1.191/grafana/public/build/manifest.979c370f20ff0db1a23c.js net::ERR_CONNECTION_TIMED_OUT
pai_clusterview:89 GET http://192.168.1.191/grafana/public/build/vendor.2305a8e1d478628b1297.js net::ERR_CONNECTION_TIMED_OUT
pai_clusterview:89 GET http://192.168.1.191/grafana/public/build/app.5331f559bd9a1bed9a93.js net::ERR_CONNECTION_TIMED_OUT

I wonder these is a bug in webportal.

**Comment by Gerhut** [comment] 2018-08-24 02:46
Hi @boozyguo, may I confirm your issue is that you are visiting <http://114.250.x.x/> with default HTTP port and the page is requesting <http://192.168.1.191/grafana/>?  

It looks wired that the Grafana's URI has been replaced by pylon as the host is not changed.

Ping @hwuu for help.

**Comment by boozyguo** [comment] 2018-08-24 05:02
hello @Gerhut , 

I deploy PAI on a single server with ip 192.168.1.191.  The server can be  visitted  by nginx‘s IP:PORT mapping.

mapping details as below:
192.168.1.191:80 is mapped to 114.250.x.x:31088.
192.168.1.191:9090 mapped to 114.250.x.x:31089
192.168.1.191:9086 mapped to 114.250.x.x:31082
192.168.1.191:9186 mapped to 114.250.x.x:31083
192.168.1.191:9286 mapped to 114.250.x.x:31084
192.168.1.191:3000 mapped to 114.250.x.x:31085
192.168.1.191:9091 mapped to 114.250.x.x:31086
192.168.1.191:9100 mapped to 114.250.x.x:31087

So, when open webpage Http://114.250.x.x:31088, I find the page is requesting http://192.168.1.191/grafana/.......

Also, when open webpage http://http://114.250.xx.xx:31085/dashboard/db/pai_clusterview?refresh=30s&orgId=1,   I find the page is requesting http://192.168.1.191:9091/api/v1/query_range?/.......

**Comment by boozyguo** [comment] 2018-09-04 06:59
Hello, @hwuu @Gerhut 
would you have some methods to fix the problem? Thank you.

**Comment by Gerhut** [comment] 2018-09-04 07:11
Hi @boozyguo 

Since I cannot figure out which version you deployed, could you please show your `http://114.250.x.x:31088/scripts/env.js` if exists?

**Comment by boozyguo** [comment] 2018-09-04 07:33
Thank you @Gerhut 
the response is “{"message":"Page not found","error":{}}”

I deploy PAI platform following “https://github.com/Microsoft/pai/blob/master/pai-management/doc/cluster-bootup.md#singlebox”
I guess the version of PAI is the latest master branch.

**Comment by Gerhut** [comment] 2018-09-04 07:49
How do you map those ports? By an nginx configured by yourself?

**Comment by boozyguo** [comment] 2018-09-04 09:27
hello, @Gerhut 

I deploy PAI on a single server with ip 192.168.1.191. The server can be visitted by nginx‘s IP:PORT mapping.

mapping details as below:
192.168.1.191:80 is mapped to 114.250.x.x:31088.
192.168.1.191:9090 mapped to 114.250.x.x:31089
192.168.1.191:9086 mapped to 114.250.x.x:31082
192.168.1.191:9186 mapped to 114.250.x.x:31083
192.168.1.191:9286 mapped to 114.250.x.x:31084
192.168.1.191:3000 mapped to 114.250.x.x:31085
192.168.1.191:9091 mapped to 114.250.x.x:31086
192.168.1.191:9100 mapped to 114.250.x.x:31087

**Comment by Gerhut** [comment] 2018-09-05 03:01
Hi @boozyguo 

I think this should may be caused by lacking of `Host` header

If you do this port mapping by `proxy_pass` of nginx, make sure that you transfer `Host` header as well, like

    proxy_pass http://192.168.1.191:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

**Comment by boozyguo** [comment] 2018-09-05 09:09
@Gerhut Thank you for your help.
I have try modify nginx.conf, the configure as below. But there still is some problem.

[root@mtg192 nginx]# cat nginx.conf
# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       79 default_server;
        listen       [::]:79 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }



    server {
        listen       31080 default_server;
        listen       [::]:31080 default_server;
        server_name  pai_8042;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
              #proxy_pass     http://192.168.1.191:31089;
              proxy_pass     http://192.168.1.191:8042;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }





    server {
        listen       31089 default_server;
        listen       [::]:31089 default_server;
        server_name  pai_9090;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
              #proxy_pass     http://192.168.1.191:31089;
              proxy_pass     http://192.168.1.191:9090;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }


    server {
        listen       31082 default_server;
        listen       [::]:31082 default_server;
        server_name  pai_9086;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
              #proxy_pass     http://192.168.1.191:31082;
              proxy_pass     http://192.168.1.191:9086;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

    server {
        listen       31083 default_server;
        listen       [::]:31083 default_server;
        server_name  pai_9186;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
              #proxy_pass     http://192.168.1.191:31083;
              proxy_pass     http://192.168.1.191:9186;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }



    server {
        listen       31084 default_server;
        listen       [::]:31084 default_server;
        server_name  pai_9286;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
              #proxy_pass     http://192.168.1.191:31084;
              proxy_pass     http://192.168.1.191:9286;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }


    server {
        listen       31085 default_server;
        listen       [::]:31085 default_server;
        server_name  pai_3000;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
              #proxy_pass     http://192.168.1.191:31085;
              proxy_pass     http://192.168.1.191:3000;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }


    server {
        listen       31086 default_server;
        listen       [::]:31086 default_server;
        server_name  pai_9091;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
              #proxy_pass     http://192.168.1.191:31086;
              proxy_pass     http://192.168.1.191:9091;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }


    server {
        listen       31087 default_server;
        listen       [::]:31087 default_server;
        server_name  pai_9100;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
              proxy_pass     http://192.168.1.191:31087;
              #proxy_pass     http://192.168.1.191:9100;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }



    server {
        listen       31088 default_server;
        listen       [::]:31088 default_server;
        server_name  pai_80;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
              #proxy_pass     http://192.168.1.191:31088;
              proxy_pass     http://192.168.1.191:80;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

![default](https://user-images.githubusercontent.com/20755762/45083429-653e6500-b12e-11e8-8a22-5aecf3129b1c.png)
 

![default](https://user-images.githubusercontent.com/20755762/45082293-9701fc80-b12b-11e8-8bb0-fabbef3c86db.png)

**Comment by Gerhut** [comment] 2018-09-06 04:03
It looks like you are using master branch, which does not include #1119 in the 0.7.1 release. Could you please upgrade the system to our release version?

I am emulating your nginx environment to figure out the root cause, thank you for your patience.

**Comment by Gerhut** [comment] 2018-09-06 07:04
Hi @boozyguo 

Could you please change your `proxy_set_header Host` from `$host` to `$http_host`? Due to [`$host` does not includes port of HTTP_HOST header](https://nginx.org/en/docs/http/ngx_http_core_module.html#var_host)

**Comment by Gerhut** [comment] 2018-09-06 08:29
It looks like Prometheus cannot product metrics of Grafana cannot grab them.

@YitongFeng @xudifsd Could you give some suggestions?

**Comment by boozyguo** [comment] 2018-09-06 08:31
Hi @Gerhut 
I deploy PAI using the master version of API, because there is some network problems in other old version of PAI. 

Using the master branch version,  if click "Hardware" lable, some errors will be reported:

![default](https://user-images.githubusercontent.com/20755762/45144954-16f29a00-b1f2-11e8-9329-e78367ac7304.png)

**Comment by Gerhut** [comment] 2018-09-06 08:42
Hi @boozyguo 

As I [said](#issuecomment-418957613), this fix is in v0.7.1 release version of PAI, but not merged into master branch yet.

So please checkout release stable version to deploy.

**Comment by xudifsd** [comment] 2018-09-06 09:17
@boozyguo What's your node-exporter & grafana's version. You can get their version in K8s Dashboard like:

![image](https://user-images.githubusercontent.com/665253/45147893-984d2b00-b1f8-11e8-8856-934459af2bcd.png)

And what's the status of node-exporter, is the service up and running?

**Comment by boozyguo** [comment] 2018-09-07 01:58
hello, @xudifsd 
the version of node-exporter & grafana, and the status  as below:

![default](https://user-images.githubusercontent.com/20755762/45194076-0e4aa400-b284-11e8-9b58-8b21e7248a0d.png)

![default](https://user-images.githubusercontent.com/20755762/45194151-5ff32e80-b284-11e8-8cce-80ed397162ee.png)

![default](https://user-images.githubusercontent.com/20755762/45194195-9df05280-b284-11e8-99c2-67d6e94eb70a.png)

**Comment by xudifsd** [comment] 2018-09-07 04:57
@boozyguo Thanks, I suspect this is due to #987 not included in your grafana image. You can edit json config in grafana page to see its config. From here:

![image](https://user-images.githubusercontent.com/665253/45199182-f7fd1200-b29c-11e8-9b44-86c03fc063c8.png)

and check its config is:

![image](https://user-images.githubusercontent.com/665253/45199211-13681d00-b29d-11e8-932e-01622fec88a6.png)

If it's not `node_cpu_seconds_total` you should upgrade your grafana code by fetching & merging master branch.

If it is, maybe node-exporter is not functioning right, you can check that from prometheus's page which located in port 9091

![image](https://user-images.githubusercontent.com/665253/45199330-a1dc9e80-b29d-11e8-83bb-1a91a6e96bff.png)

**Comment by xudifsd** [comment] 2018-09-10 02:03
@boozyguo Hi, your config for grafana is not the latest, please use latest code to deploy:

```
git fetch origin
git merge origin/master
cd pai-management
./paictl.py service stop -p /path/to/config -n grafana
./paictl.py service start -p /path/to/config -n grafana
```

Above commands should update your config.

**Comment by boozyguo** [comment] 2018-09-10 03:08
hello, @xudifsd 
I try the above commands to update grafana, but the service of grafana can not be restarted:
![default](https://user-images.githubusercontent.com/20755762/45274352-b57c4500-b4e9-11e8-83db-05be34b18c5a.png)

**Comment by xudifsd** [comment] 2018-09-10 03:35
@boozyguo I see, this is a break change introduced by #1081 . You can solve this by redeploy whole k8s. Or you can deploy 0.7.1 version. I suggest you deploy 0.7.1 version, you can do this by

```
git checkout origin/pai-0.7.y -b pai-0.7.y
# change your config in `services-configuration.yaml`. Change `docker-tag` to `v0.7.1`
cd pai-management
./paictl.py service stop -p /path/to/config # stop all services
./paictl.py service start -p /path/to/config # start all services
```

**Comment by boozyguo** [comment] 2018-09-10 07:02
Thanks @xudifsd 
I have try to deploy 0.7.1 version, but some error reported:

2018-09-10 15:00:30,657 [INFO] - paiLibrary.paiService.service_start : Begin to execute service pylon's start script.
node/192.168.1.191 labeled
daemonset.apps/pylon-ds created
2018-09-10 15:00:31,152 [INFO] - paiLibrary.paiService.service_management_start : Begin to clean all service's generated template file
2018-09-10 15:00:31,153 [INFO] - paiLibrary.paiService.service_template_clean : Begin to delete the generated template of pylon's service.
2018-09-10 15:00:31,153 [INFO] - paiLibrary.paiService.service_template_clean : The generated template files of pylon's  service have been cleaned up.
2018-09-10 15:00:31,154 [INFO] - paiLibrary.paiService.service_management_start : Successfully start pylon
2018-09-10 15:00:31,154 [INFO] - paiLibrary.paiService.service_management_start : -----------------------------------------------------------
2018-09-10 15:00:31,162 [INFO] - paiLibrary.paiService.service_management_start : -----------------------------------------------------------
2018-09-10 15:00:31,184 [INFO] - paiLibrary.paiService.service_management_start : Begin to generate service webportal's template file
2018-09-10 15:00:31,184 [INFO] - paiLibrary.paiService.service_template_generate : Begin to generate the template file in service webportal's configuration.
2018-09-10 15:00:31,185 [INFO] - paiLibrary.paiService.service_template_generate : Create template mapper for service webportal.
2018-09-10 15:00:31,185 [INFO] - paiLibrary.paiService.service_template_generate : Done. Template mapper for service webportal is created.
2018-09-10 15:00:31,186 [INFO] - paiLibrary.paiService.service_template_generate : Generate the template file bootstrap/webportal/node-label.sh.template.
2018-09-10 15:00:31,186 [INFO] - paiLibrary.paiService.service_template_generate : Save the generated file to bootstrap/webportal/node-label.sh.
2018-09-10 15:00:31,193 [INFO] - paiLibrary.paiService.service_template_generate : Generate the template file bootstrap/webportal/webportal.yaml.template.
2018-09-10 15:00:31,193 [INFO] - paiLibrary.paiService.service_template_generate : Save the generated file to bootstrap/webportal/webportal.yaml.
2018-09-10 15:00:31,204 [ERROR] - paiLibrary.paiService.service_template_generate : failed to generate template file from bootstrap/webportal/webportal.yaml.template with dict {'machinelist': {'mtg191': {'webportal': 'true', 'ip': '192.168.1.191', 'zookeeper': 'true', 'pai-master': 'true', 'zkid': '1', 'pylon': 'true', 'watchdog': 'true', 'hadoop-resource-manager': 'true', 'machinetype': 'GENERIC', 'hostname': 'mtg191', 'grafana': 'true', 'pai-worker': 'true', 'username': 'ubuntu', 'hadoop-data-node': 'true', 'nodename': '192.168.1.191', 'restserver': 'true', 'prometheus': 'true', 'hadoop-node-manager': 'true', 'password': 'Xdsd@20180723', 'etcdid': 'etcdid1', 'k8s-role': 'master', 'jobhistory': 'true', 'hadoop-name-node': 'true', 'launcher': 'true', 'dashboard': 'true', 'hostip': '192.168.1.191', 'sshport': 22, 'node-exporter': 'true', 'machine-type': 'GENERIC'}}, 'machineinfo': {'GENERIC': {'mem': 1, 'gpu': {'count': 1, 'type': 'k2000'}, 'os': 'ubuntu16.04', 'cpu': {'vcore': 4}}}, 'clusterinfo': {'data-path': '/datastorage', 'prometheusinfo': {'node-exporter-port': 9100, 'node_exporter_port': 9100, 'prometheus_url': 'http://192.168.1.191', 'prometheus_port': 9091, 'prometheus-port': 9091}, 'restserverinfo': {'jwt_secret': 'pai-secret', 'hdfs_uri': 'hdfs://192.168.1.191:9000', 'default_pai_admin_password': 'admin-password', 'default-pai-admin-username': 'admin', 'etcd_uri': 'http://192.168.1.191:4001', 'webhdfs_uri': 'http://192.168.1.191:50070', 'src_path': '../rest-server/', 'server_port': 9186, 'yarn_uri': 'http://192.168.1.191:8088', 'server-port': 9186, 'webservice_uri': 'http://192.168.1.191:9086', 'default-pai-admin-password': 'admin-password', 'default_pai_admin_username': 'admin', 'jwt-secret': 'pai-secret'}, 'docker-registry-info': {'credential': '{}', 'docker-namespace': 'openpai', 'secret-name': 'pai-secret', 'base64code': 'e30=', 'docker_password': None, 'secretname': 'pai-secret', 'docker_username': None, 'prefix': 'docker.io/openpai/', 'docker_tag': 'v0.7.1', 'docker-tag': 'v0.7.1', 'docker-registry-domain': 'docker.io', 'docker_namespace': 'openpai', 'docker_registry_domain': 'docker.io'}, 'nvidia-drivers-version': 384.111, 'grafanainfo': {'grafana_url': 'http://192.168.1.191', 'grafana-port': 3000, 'grafana_port': 3000}, 'clusterid': 'pai-example', 'dataPath': '/datastorage', 'dockerregistryinfo': {'credential': '{}', 'docker-namespace': 'openpai', 'secret-name': 'pai-secret', 'base64code': 'e30=', 'docker_password': None, 'secretname': 'pai-secret', 'docker_username': None, 'prefix': 'docker.io/openpai/', 'docker_tag': 'v0.7.1', 'docker-tag': 'v0.7.1', 'docker-registry-domain': 'docker.io', 'docker_namespace': 'openpai', 'docker_registry_domain': 'docker.io'}, 'docker-verison': '17.06.2', 'hadoopQueues': {'default': {'description': 'Default VC.', 'weight': 100.0}}, 'webportalinfo': {'prometheus_uri': 'http://192.168.1.191:9091', 'k8s_dashboard_uri': 'http://192.168.1.191:9090', 'rest_server_uri': 'http://192.168.1.191:9186', 'grafana_uri': 'http://192.168.1.191:3000', 'server_port': 9286, 'k8s_api_server_uri': 'http://192.168.1.191:8080', 'server-port': 9286, 'yarn_web_portal_uri': 'http://192.168.1.191:8088'}, 'hadoopinfo': {'configmapname': 'hadoop-configuration', 'custom-hadoop-binary-path': '/pathHadoop/hadoop-2.7.2.tar.gz', 'custom_hadoop_binary_path': '/pathHadoop/hadoop-2.7.2.tar.gz', 'hadoopversion': '2.7.2', 'hadoop-version': '192.168.1.191', 'hadoop_vip': '192.168.1.191'}, 'frameworklauncher': {'frameworklauncher_port': 9086, 'frameworklauncher_vip': '192.168.1.191', 'frameworklauncher-port': 9086}, 'pyloninfo': {'prometheus_uri': 'http://192.168.1.191:9091', 'k8s_dashboard_uri': 'http://192.168.1.191:9090', 'rest_server_uri': 'http://192.168.1.191:9186', 'webhdfs_uri': 'http://192.168.1.191:50070', 'pai_web_portal_uri': 'http://192.168.1.191:9286', 'grafana_uri': 'http://192.168.1.191:3000', 'k8s_api_server_uri': 'http://192.168.1.191:8080', 'port': 80, 'yarn_web_portal_uri': 'http://192.168.1.191:8088'}, 'virtualClusters': {'default': {'capacity': 1, 'description': 'Default VC.'}}}}
Traceback (most recent call last):
  File "/pai/pai-management/paiLibrary/paiService/service_template_generate.py", line 82, in generate_template
    generated_template = template_handler.generate_from_template_dict(template_data, service_conf_dict)
  File "/pai/pai-management/paiLibrary/common/template_handler.py", line 28, in generate_from_template_dict
    map_table
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 56, in top-level template code
UndefinedError: 'dict object' has no attribute 'scrape_interval'
Traceback (most recent call last):
  File "./paictl.py", line 623, in <module>
    main()
  File "./paictl.py", line 608, in main
    pai_service()
  File "./paictl.py", line 467, in pai_service
    service_management_starter.run()
  File "/pai/pai-management/paiLibrary/paiService/service_management_start.py", line 111, in run
    self.start(serv)
  File "/pai/pai-management/paiLibrary/paiService/service_management_start.py", line 84, in start
    service_template_generater.run()
  File "/pai/pai-management/paiLibrary/paiService/service_template_generate.py", line 95, in run
    self.generate_template()
  File "/pai/pai-management/paiLibrary/paiService/service_template_generate.py", line 85, in generate_template
    raise e
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'scrape_interval

**Comment by xudifsd** [comment] 2018-09-10 08:17
You should add `scrape_interval: 30` to your `services-configuration.yam` like [here](https://github.com/Microsoft/pai/blob/master/cluster-configuration/services-configuration.yaml#L106)

**Comment by boozyguo** [comment] 2018-09-11 06:13
hello, @xudifsd   thank you for your help. 
I have add "scrape_interval: 30" to the services-configuration.yam. The webportal works!
however, there is no data in JobLevelMetrics, TaskRoleLevelMetrics, and TaskLevelMetrics, so is it right?

![default](https://user-images.githubusercontent.com/20755762/45341260-930f2800-b5cc-11e8-966f-d9f81596e55a.png)

**Comment by xudifsd** [comment] 2018-09-11 06:58
This is expected. You should visit jobLevel/taskRole/taskLevel metrics from jobs->specific job->job metrics. And only running jobs have data points.

**Comment by boozyguo** [comment] 2018-09-12 07:42
thanks @xudifsd . 
I update the system to version 0.7.1, the webportal is working now.

**Closed** 2018-09-13 02:04 UTC
