### ISSUE TITLE
kubernetes cannot be installed

### ISSUE THREAD

**Issue by Michellechen78** [Microsoft/pai#1548] opened 2018-10-18 02:01 UTC
Environment：
gpu：tesla v100
cpu:：Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
Ubuntu 16.04.5

Followed this (https://github.com/Microsoft/pai) procedure，docker image still old version.
Then we get other url https://www.cnblogs.com/ms-uap/p/openpai_or_pai.html but the kubernetes cannot be innstalled.
when we run "python paictl.py cluster k8s-bootup -p $CONFIG_PATH"
the procedure quite and  windows closed.
We are trapped here. Pls help us fix this issue.

**Comment by Michellechen78** [comment] 2018-10-18 02:04
the screenshots as follows:
![1](https://user-images.githubusercontent.com/43133379/47126800-dab85c00-d2bc-11e8-9d0d-018e3223dbc1.png)

![2](https://user-images.githubusercontent.com/43133379/47126807-e015a680-d2bc-11e8-8f59-f9cb0df4ecf8.png)

![3](https://user-images.githubusercontent.com/43133379/47126824-f459a380-d2bc-11e8-95fe-2df4fdbd95cb.png)

![4](https://user-images.githubusercontent.com/43133379/47126827-fa4f8480-d2bc-11e8-8902-496154d8810b.png)

![5](https://user-images.githubusercontent.com/43133379/47126832-03405600-d2bd-11e8-9bcd-a589ebed241e.png)

![6](https://user-images.githubusercontent.com/43133379/47126837-0cc9be00-d2bd-11e8-809f-6b7c3b43f212.png)

**Comment by ydye** [comment] 2018-10-18 02:12
@Michellechen78    Did you deploy pai on a single-box mode? And the Dev-box is in the same host machine where you wanna deploy pai?

**Comment by NothingLZ** [comment] 2018-10-18 02:14
> @Michellechen78 Did you deploy pai on a single-box mode? And the Dev-box is in the same host machine where you wanna deploy pai?

yes

**Comment by ydye** [comment] 2018-10-18 02:30
And by the way, now, we have a public registry to provide the latest released serivce's image, and user do not need building image by themselves. 
https://github.com/Microsoft/pai/blob/master/docs/pai-management/doc/how-to-write-pai-configuration.md#services_configuration

**Comment by NothingLZ** [comment] 2018-10-18 03:07
> 很抱歉不方便，这是dev-box的一个已知问题。因为在部署kubernetes时，paictl会尝试为docker-daemon启用日志轮换功能，以避免大量使用contianer的日志。因此，我们将在目标节点上重新启动docker-daemon以启用配置。因此，当dev-box在环境中时，由于docker-d的重启，它将被停止。
> 
> 以下是部署单机时解决此问题的解决方案。这里有另外一个[问题，](https://github.com/Microsoft/pai/issues/1283)同样的问题。
> 
> #### 解
> 克隆pai在本地主机上的回购（不要使用dev-box）。并安装依赖包。然后在主机环境中使用paictl。
> 
> ```
> apt-get -y update && \
> apt-get -y install \
>       nano \
>       vim \
>       joe \
>       wget \
>       curl \
>       jq \
>       gawk \
>       psmisc \
>       python \
>       python-yaml \
>       python-jinja2 \
>       python-paramiko \
>       python-urllib3 \
>       python-tz \
>       python-nose \
>       python-prettytable \
>       python-netifaces \
>       python-dev \
>       python-pip \
>       python-mysqldb \
>       openssh-server \
>       openssh-client \
>       git \
>       bash-completion \
>       inotify-tools \
>       rsync \
>       realpath \
>       net-tools && \
>     mkdir -p /cluster-configuration &&\
>     pip install python-etcd docker kubernetes GitPython
> ```

Should I use the CPU node as the master and the GUP node as the work. Is this deployed?

**Comment by ydye** [comment] 2018-10-18 03:13
Yes, Cpu node shoud be master, and the Gpu node shoud be work. And one thing important is that don't run the dev-box in your OpenPai cluster, or you will occurs the issue this time again due to the restart of docker-daemon.

**Comment by NothingLZ** [comment] 2018-10-18 03:30
> Yes, Cpu node shoud be master, and the Gpu node shoud be work. And one thing important is that don't run the dev-box in your OpenPai cluster, or you will occurs the issue this time again due to the restart of docker-daemon.

Pull a ubuntu:16.04 docker image and create a ubuntu:16.04 container,then clone pai in the / directory. Upgrade the following software before this.
apt-get -y update && 
apt-get -y install 
nano 
vim 
joe 
wget 
curl 
jq 
gawk 
psmisc 
python 
python-yaml 
python-jinja2 
python-paramiko 
python-urllib3 
python-tz 
python-nose 
python-prettytable 
python-netifaces 
python-dev 
python-pip 
python-mysqldb 
openssh-server 
openssh-client 
git 
bash-completion 
inotify-tools 
rsync 
realpath 
net-tools && 
mkdir -p /cluster-configuration &&
pip install python-etcd docker kubernetes GitPython

**Comment by ydye** [comment] 2018-10-18 03:36
If you wanna **deploy OpenPai** in **a host which belongs to the OpenPai cluster**. Please don't do any operate in a docker container, because it will be stopped when restarting docker-d. 
You should install the dependency package on the local environment of that host, and then follow the steps to install OpenPai.

**Comment by ydye** [comment] 2018-10-18 09:08
Little confused about your question. Are there 2 different question? 
And for the questions
```
Is it necessary to install cuda and cudnn?
```
The answer is no. Please don't install any nvidia drivers on the gpu machine. Paictl will start the drivers one shot service to do it.

**Comment by NothingLZ** [comment] 2018-10-18 10:32
> @NothingLZ
> Little confused about your question. Are there 2 different question?
> And for the questions
> 
> ```
> Is it necessary to install cuda and cudnn?
> ```
> The answer is no. Please don't install any nvidia drivers on the gpu machine. Paictl will start the drivers one shot service to do it.
> 
> And for the question
> 
> ```
> Do GPU nodes need to deploy the hadoopAI environment in advance? 
> ```
> I think the environment of hadoopAI can be setup by paictl.

My previous hadoopAI environment was built according to https://github.com/Microsoft/pai/tree/master/src/hadoop-ai/build. I don't know how to build it with paictl?

**Comment by ydye** [comment] 2018-10-18 12:40
With the latest release, you could build all OpenPai's service with the tool pai-build.  Please refer to this [link](https://github.com/Microsoft/pai/blob/master/docs/pai-build/pai-build.md#build).

**Comment by NothingLZ** [comment] 2018-10-19 03:55
root@mic:/home/pai/build# ./pai_build.py build -c /path/to/configuration-dir/
2018-10-19 11:53:24,664 - __main__ - INFO - Pai build starts at 2018-10-19 11:53:24.663910
2018-10-19 11:53:24,689 - core.build_utility - INFO - Begin to execute the command: docker login -u None -p None docker.io
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
2018-10-19 11:53:31,596 - core.build_utility - INFO - Executing command failed: docker login -u None -p None docker.io

Is it necessary to configure username and password?

**Comment by ydye** [comment] 2018-10-19 06:06
Yes, you should configure password and username

And you can alson use the image we published.
```
docker-registry-info:
  - docker-namespace: openpai
  - docker-registry-domain: docker.io
  #- docker-username: <n/a>
  #- docker-password: <n/a>
  - docker-tag: latest # or a specific version, i.e. 0.5.0.
  - secret-name: <anything>
```

**Comment by NothingLZ** [comment] 2018-10-19 09:50
Sorry, I didn't figure it out. Is your image hosted in hub.docker.com? So what is the image name? Can I pull it directly?

**Comment by NothingLZ** [comment] 2018-10-22 08:22
I tried to build a row of pai locally, but there was an error.

WARNING: No swap limit support
Docker ROOT DIR IS /var/lib/docker
Unable to find image 'gcr.io/google_containers/hyperkube:v1.9.9' locally
gcr.io/google_containers/hyperkube:v1.9.9docker: Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp 74.125.203.82:443: i/o timeout.
See 'docker run --help'.

**Comment by ydye** [comment] 2018-10-22 08:37
Can you access to gcr.io? If not, please change the configuration in the kubernetes-configuration.yaml as following.
```
  docker-registry: docker.io/openpai
```

**Comment by NothingLZ** [comment] 2018-10-22 09:11
2018-10-22 16:56:57,645 [INFO] - deployment.k8sPaiLibrary.maintainlib.deploy :  remote host cleaning job finished! 
2018-10-22 16:56:57,645 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Execute the script to install kubectl on your host!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   213  100   213    0     0    259      0 --:--:-- --:--:-- --:--:--   259
2018-10-22 17:01:17,481 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Generate the configuation file of kubectl.
/usr/local/bin/kubectl: 1: /usr/local/bin/kubectl: Syntax error: redirection unexpected
2018-10-22 17:01:17,488 [WARNING] - deployment.k8sPaiLibrary.maintainlib.common : There will be a delay after installing, please wait.
2018-10-22 17:01:17,488 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Wait 5s, and retry it later.
/usr/local/bin/kubectl: 1: /usr/local/bin/kubectl: Syntax error: redirection unexpected
2018-10-22 17:01:22,498 [WARNING] - deployment.k8sPaiLibrary.maintainlib.common : There will be a delay after installing, please wait.
2018-10-22 17:01:22,499 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Wait 5s, and retry it later.
/usr/local/bin/kubectl: 1: /usr/local/bin/kubectl: Syntax error: redirection unexpected
2018-10-22 17:01:27,510 [WARNING] - deployment.k8sPaiLibrary.maintainlib.common : There will be a delay after installing, please wait.
2018-10-22 17:01:27,511 [INFO] - deployment.k8sPaiLibrary.maintainlib.kubectl_install : Wait 5s, and retry it later.
/usr/local/bin/kubectl: 1: /usr/local/bin/kubectl: Syntax error: redirection unexpected


The program is always looping

**Comment by ydye** [comment] 2018-10-23 02:06
Can you ssh to the target machine. And execute the command following, and show me the result?
```
sudo docker ps -a
```

**Comment by ydye** [comment] 2018-10-23 02:31
And can you paste the log of kubelet with the command?
```
sudo docker logs kubelet
```

**Comment by NothingLZ** [comment] 2018-10-23 02:46
I1022 10:03:16.426925   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/git-repo"
I1022 10:03:16.426930   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/host-path"
I1022 10:03:16.426935   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/nfs"
I1022 10:03:16.426939   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/secret"
I1022 10:03:16.426944   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/iscsi"
I1022 10:03:16.426951   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/glusterfs"
I1022 10:03:16.426956   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/rbd"
I1022 10:03:16.426961   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/cinder"
I1022 10:03:16.426966   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/quobyte"
I1022 10:03:16.426970   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/cephfs"
I1022 10:03:16.426977   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/downward-api"
I1022 10:03:16.426981   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/fc"
I1022 10:03:16.426985   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/flocker"
I1022 10:03:16.426990   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/azure-file"
I1022 10:03:16.426995   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/configmap"
I1022 10:03:16.427001   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/vsphere-volume"
I1022 10:03:16.427005   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/azure-disk"
I1022 10:03:16.427010   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/photon-pd"
I1022 10:03:16.427014   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/projected"
I1022 10:03:16.427019   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/portworx-volume"
I1022 10:03:16.427027   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/scaleio"
I1022 10:03:16.427054   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/local-volume"
I1022 10:03:16.427062   26823 plugins.go:453] Loaded volume plugin "kubernetes.io/storageos"
I1022 10:03:16.427842   26823 server.go:758] Started kubelet
E1022 10:03:16.428317   26823 kubelet.go:1287] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
I1022 10:03:16.429581   26823 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
I1022 10:03:16.429744   26823 server.go:129] Starting to listen on 10.10.25.228:10250
I1022 10:03:16.430312   26823 server.go:299] Adding debug handlers to kubelet server.
I1022 10:03:16.431424   26823 server.go:149] Starting to listen read-only on 10.10.25.228:10255
E1022 10:03:16.441654   26823 event.go:209] Unable to write event: 'Post http://10.10.25.228:8080/api/v1/namespaces/default/events: dial tcp 10.10.25.228:8080: getsockopt: connection refused' (may retry after sleeping)
I1022 10:03:16.447158   26823 kubelet_node_status.go:434] Recording NodeHasSufficientDisk event message for node 10.10.25.228
I1022 10:03:16.447180   26823 kubelet_node_status.go:434] Recording NodeHasSufficientMemory event message for node 10.10.25.228
I1022 10:03:16.447186   26823 kubelet_node_status.go:434] Recording NodeHasNoDiskPressure event message for node 10.10.25.228
F1022 10:03:16.447227   26823 kubelet.go:1376] Failed to start ContainerManager Invalid Node Allocatable configuration. Resource "memory" has an allocatable of {{4294967296 0} {<nil>}  BinarySI}, capacity of {{-2197278720 0} {<nil>}  BinarySI}

Oh, I think it is caused by insufficient memory?

**Comment by ydye** [comment] 2018-10-23 02:53
And can you watch the mem usage in your system with the following command?
```
free -h
```

**Comment by ustcjerry** [comment] 2018-10-23 02:55
> I1022 10:03:16.426925 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/git-repo"
> I1022 10:03:16.426930 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/host-path"
> I1022 10:03:16.426935 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/nfs"
> I1022 10:03:16.426939 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/secret"
> I1022 10:03:16.426944 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/iscsi"
> I1022 10:03:16.426951 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/glusterfs"
> I1022 10:03:16.426956 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/rbd"
> I1022 10:03:16.426961 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/cinder"
> I1022 10:03:16.426966 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/quobyte"
> I1022 10:03:16.426970 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/cephfs"
> I1022 10:03:16.426977 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/downward-api"
> I1022 10:03:16.426981 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/fc"
> I1022 10:03:16.426985 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/flocker"
> I1022 10:03:16.426990 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/azure-file"
> I1022 10:03:16.426995 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/configmap"
> I1022 10:03:16.427001 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/vsphere-volume"
> I1022 10:03:16.427005 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/azure-disk"
> I1022 10:03:16.427010 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/photon-pd"
> I1022 10:03:16.427014 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/projected"
> I1022 10:03:16.427019 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/portworx-volume"
> I1022 10:03:16.427027 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/scaleio"
> I1022 10:03:16.427054 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/local-volume"
> I1022 10:03:16.427062 26823 plugins.go:453] Loaded volume plugin "kubernetes.io/storageos"
> I1022 10:03:16.427842 26823 server.go:758] Started kubelet
> E1022 10:03:16.428317 26823 kubelet.go:1287] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
> I1022 10:03:16.429581 26823 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
> I1022 10:03:16.429744 26823 server.go:129] Starting to listen on 10.10.25.228:10250
> I1022 10:03:16.430312 26823 server.go:299] Adding debug handlers to kubelet server.
> I1022 10:03:16.431424 26823 server.go:149] Starting to listen read-only on 10.10.25.228:10255
> E1022 10:03:16.441654 26823 event.go:209] Unable to write event: 'Post http://10.10.25.228:8080/api/v1/namespaces/default/events: dial tcp 10.10.25.228:8080: getsockopt: connection refused' (may retry after sleeping)
> I1022 10:03:16.447158 26823 kubelet_node_status.go:434] Recording NodeHasSufficientDisk event message for node 10.10.25.228
> I1022 10:03:16.447180 26823 kubelet_node_status.go:434] Recording NodeHasSufficientMemory event message for node 10.10.25.228
> I1022 10:03:16.447186 26823 kubelet_node_status.go:434] Recording NodeHasNoDiskPressure event message for node 10.10.25.228
> F1022 10:03:16.447227 26823 kubelet.go:1376] Failed to start ContainerManager Invalid Node Allocatable configuration. Resource "memory" has an allocatable of {{4294967296 0} {} BinarySI}, capacity of {{-2197278720 0} {} BinarySI}
> 
> Oh, I think it is caused by insufficient memory?

Hello NothingLZ please see my updated blog, you need at least 12G mem. More is better.
https://www.cnblogs.com/jins-note/p/9673883.html

**Comment by NothingLZ** [comment] 2018-10-23 02:57
![image](https://user-images.githubusercontent.com/12367891/47332622-66156100-d6b2-11e8-834f-28d443920052.png)

**Comment by NothingLZ** [comment] 2018-10-23 02:58
I deployed it on the GPU host or this result.
![image](https://user-images.githubusercontent.com/12367891/47332670-9826c300-d6b2-11e8-9727-e3105fdcfccc.png)

**Comment by NothingLZ** [comment] 2018-10-23 03:00
![image](https://user-images.githubusercontent.com/12367891/47332726-cdcbac00-d6b2-11e8-8235-663bf784ee2f.png)

**Comment by NothingLZ** [comment] 2018-10-23 03:01
Use a local machine to configure the remote GPU cloud host.

**Comment by ustcjerry** [comment] 2018-10-23 03:04
Maybe you can try to clean all the docker image especially related to the kubernetes and redeploy.
docker ps -a
docker rm <container id>
docker rmi <image id>

**Comment by NothingLZ** [comment] 2018-10-23 03:09
> 也许你可以尝试清理所有与kubernetes相关的docker镜像并重新部署。
> docker ps -a 
> docker 
> rm'container id'docker rmi'image id'

Ok, I redeployed it.

**Comment by ydye** [comment] 2018-10-23 03:40
> I deployed it on the GPU host or this result.
> ![image](https://user-images.githubusercontent.com/12367891/47332670-9826c300-d6b2-11e8-9727-e3105fdcfccc.png)

Please be sure that the following ```IP``` has been replaced by the ip-address of your master machine.

**Comment by NothingLZ** [comment] 2018-10-24 04:18
![image](https://user-images.githubusercontent.com/12367891/47405966-f1f8bd00-d786-11e8-843c-21995226207e.png)

**Comment by ydye** [comment] 2018-10-24 06:11
Did the kubelet still fail due to the same reason? Can you paste the log again?

**Comment by NothingLZ** [comment] 2018-10-24 06:16
I use A to deploy B and C, the master node is the B working node is C.

http://master:9090
![image](https://user-images.githubusercontent.com/12367891/47410130-68052000-d797-11e8-94e9-995fcc34da0a.png)

**Comment by ydye** [comment] 2018-10-24 06:52
I think the kubernetes is deployed successfully. And It seems there are some issues when deploying pai-service.

**Comment by NothingLZ** [comment] 2018-10-30 06:14
![image](https://user-images.githubusercontent.com/12367891/47699355-90849280-dc4d-11e8-86d7-e8a28d10dc5d.png)

I use local virtual machine A to deploy remote B and C, B is master (CPU host) and C is work (GPU host).

docker  logs kubelet


![image](https://user-images.githubusercontent.com/12367891/47699509-11dc2500-dc4e-11e8-87e4-a4901cc6f7b8.png)

**Comment by ydye** [comment] 2018-11-21 05:19
Did this issue still exist?

**Comment by ydye** [comment] 2018-11-30 04:16
No continue update. close it.

**Closed by ydye** 2018-11-30 04:16 UTC
