### ISSUE TITLE
Job doesn't stop when all tasks is over

### ISSUE THREAD

**Issue by SongBiu** [Microsoft/pai#1015] opened 2018-07-31 01:30 UTC
I submit a job with some tasks and when all tasks' command are executed over, the job are still running
How about it?

**Comment by yqwang-ms** [comment] 2018-07-31 02:41
After all tasks completed, the whole job should complete soon.

Please provide below whole logs for us to debug:
![image](https://user-images.githubusercontent.com/32826762/43434355-e36f407c-94ad-11e8-8811-ad4a48963216.png)

**Comment by SongBiu** [comment] 2018-07-31 02:50
http://10.151.40.179/yarn/10.151.40.179:8088/cluster/app/application_1532509944573_0029
this is the job's url
Thanks!

**Comment by yqwang-ms** [comment] 2018-07-31 03:09
Thanks. But I see all tasks' container are still running.
So, I guess the task should be hang when exit.
@Gerhut to take a look.


http://10.151.40.179/yarn/10.151.40.169:8042/node/containerlogs/container_e9881_1532509944573_0029_01_000003/yuqian/stdout/?start=-4096

![image](https://user-images.githubusercontent.com/32826762/43435257-bd85af1e-94b1-11e8-810c-0adf4cf9049b.png)

**Comment by SongBiu** [comment] 2018-07-31 07:24
When the job is running when all task is over, all resource it held are about 100M memories.

**Comment by Gerhut** [comment] 2018-07-31 09:31
Caused by same `#PAI_TASK_INDEX` in all containers, fixed in #879

**Closed** 2018-08-06 11:53 UTC
Labels: raised by customer
