### ISSUE TITLE
Container [xxx] is running beyond virtual memory limits.

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1151] opened 2018-08-24 13:46 UTC
On a Singlebox with 120G memory, job failed because of `running beyond virtual memory limits`.

Job config:
> {
>   "jobName": "e2e-test-14499-3139",
>   "image": "aiplatform/pai.run.cntk",
>   "taskRoles": [
>     {
>       "name": "Master",
>       "taskNumber": 1,
>       "cpuNumber": 1,
>       "memoryMB": 256,
>       "gpuNumber": 0,
>       "command": "/bin/bash --version"
>     }
>   ]
> }

Application Summary:
> [ExitStatus]: CONTAINER_VIRTUAL_MEMORY_EXCEEDED
> [ExitCode]: -103
> [ExitDiagnostics]:
> Container Killed since it exceeded the request virtual memory
> [ExitType]: NON_TRANSIENT
> ________________________________________________________________________________________________________________________________________________________________________________________________________
> [ExitCustomizedDiagnostics]:
> <Raw>[ExitCode]: -103
> <Raw>[ExitDiagnostics]:
> [2018-08-24 12:42:05.888]Container [pid=116086,containerID=container_1535113754342_0003_01_000002] is running beyond virtual memory limits. Current usage: 106.2 MB of 1 GB physical memory used; 5.8 GB of 2.1 GB virtual memory used. Killing container.
> Dump of the process-tree for container_1535113754342_0003_01_000002 :
> |- PID PPID PGRPID SESSID CMD_NAME USER_MODE_TIME(MILLIS) SYSTEM_TIME(MILLIS) VMEM_USAGE(BYTES) RSSMEM_USAGE(PAGES) FULL_CMD_LINE
> |- 118134 116086 116086 116086 (bash) 0 0 18624512 586 /bin/bash -c source YarnContainerScripts/0.sh 1>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stdout 2>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stderr
> |- 116086 116084 116086 116086 (bash) 0 0 18624512 788 /bin/bash -c source YarnContainerScripts/0.sh 1>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stdout 2>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stderr
> |- 118135 118134 116086 116086 (java) 116 9 6125953024 24992 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Dproc_getconf -Xmx4096m -Djava.net.preferIPv4Stack=true -Dhadoop.log.dir=/var/log/hadoop/ -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/usr/local/hadoop -Dhadoop.id.str= -Dhadoop.root.logger=INFO,console -Djava.library.path=/usr/local/hadoop/lib/native -Dhadoop.policy.file=hadoop-policy.xml -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Stack=true -Dhadoop.log.dir=/var/log/hadoop/ -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/usr/local/hadoop -Dhadoop.id.str=admin -Dhadoop.root.logger=INFO,console -Djava.library.path=/usr/local/hadoop/lib/native -Dhadoop.policy.file=hadoop-policy.xml -Djava.net.preferIPv4Stack=true -Dhadoop.security.logger=INFO,console org.apache.hadoop.hdfs.tools.GetConf -confKey hadoop.tmp.dir
> |- 116090 116086 116086 116086 (bash) 0 0 18558976 659 /bin/bash -c source YarnContainerScripts/0.sh 1>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stdout 2>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stderr
> |- 117889 116090 116086 116086 (sleep) 0 0 4485120 170 sleep 20
> [2018-08-24 12:42:05.889]
> [2018-08-24 12:42:05.932]Container killed on request. Exit code is 143[2018-08-24 12:42:05.932]
> [2018-08-24 12:42:05.933]Container exited with a non-zero exit code 143. [2018-08-24 12:42:05.933]
> ________________________________________________________________________________________________________________________________________________________________________________________________________
> <Raw>[ExitCustomizedDiagnostics]:
> [Master]: [LastCompletedTask]: [TaskStatus]:
> {
> "taskIndex" : 0,
> "taskRoleName" : "Master",
> "taskState" : "TASK_COMPLETED",
> "taskRetryPolicyState" : {
> "retriedCount" : 0,
> "succeededRetriedCount" : 0,
> "transientNormalRetriedCount" : 0,
> "transientConflictRetriedCount" : 0,
> "nonTransientRetriedCount" : 0,
> "unKnownRetriedCount" : 0
> },
> "taskCreatedTimestamp" : 1535114501146,
> "taskCompletedTimestamp" : 1535114526046,
> "taskServiceStatus" : {
> "serviceVersion" : 0
> },
> "containerId" : "container_1535113754342_0003_01_000002",
> "containerHost" : "10.0.1.6",
> "containerIp" : "10.0.1.6",
> "containerPorts" : "http:26619;ssh:26620;",
> "containerGpus" : 0,
> "containerLogHttpAddress" : "http://10.0.1.6:8042/node/containerlogs/container_1535113754342_0003_01_000002/admin/",
> "containerConnectionLostCount" : 0,
> "containerIsDecommissioning" : null,
> "containerLaunchedTimestamp" : 1535114503043,
> "containerCompletedTimestamp" : 1535114526044,
> "containerExitCode" : -103,
> "containerExitDiagnostics" : "[2018-08-24 12:42:05.888]Container [pid=116086,containerID=container_1535113754342_0003_01_000002] is running beyond virtual memory limits. Current usage: 106.2 MB of 1 GB physical memory used; 5.8 GB of 2.1 GB virtual memory used. Killing container.\nDump of the process-tree for container_1535113754342_0003_01_000002 :\n\t|- PID PPID PGRPID SESSID CMD_NAME USER_MODE_TIME(MILLIS) SYSTEM_TIME(MILLIS) VMEM_USAGE(BYTES) RSSMEM_USAGE(PAGES) FULL_CMD_LINE\n\t|- 118134 116086 116086 116086 (bash) 0 0 18624512 586 /bin/bash -c source YarnContainerScripts/0.sh 1>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stdout 2>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stderr \n\t|- 116086 116084 116086 116086 (bash) 0 0 18624512 788 /bin/bash -c source YarnContainerScripts/0.sh 1>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stdout 2>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stderr \n\t|- 118135 118134 116086 116086 (java) 116 9 6125953024 24992 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Dproc_getconf -Xmx4096m -Djava.net.preferIPv4Stack=true -Dhadoop.log.dir=/var/log/hadoop/ -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/usr/local/hadoop -Dhadoop.id.str= -Dhadoop.root.logger=INFO,console -Djava.library.path=/usr/local/hadoop/lib/native -Dhadoop.policy.file=hadoop-policy.xml -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Stack=true -Dhadoop.log.dir=/var/log/hadoop/ -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/usr/local/hadoop -Dhadoop.id.str=admin -Dhadoop.root.logger=INFO,console -Djava.library.path=/usr/local/hadoop/lib/native -Dhadoop.policy.file=hadoop-policy.xml -Djava.net.preferIPv4Stack=true -Dhadoop.security.logger=INFO,console org.apache.hadoop.hdfs.tools.GetConf -confKey hadoop.tmp.dir \n\t|- 116090 116086 116086 116086 (bash) 0 0 18558976 659 /bin/bash -c source YarnContainerScripts/0.sh 1>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stdout 2>/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002/stderr \n\t|- 117889 116090 116086 116086 (sleep) 0 0 4485120 170 sleep 20 \n[2018-08-24 12:42:05.889]\n[2018-08-24 12:42:05.932]Container killed on request. Exit code is 143[2018-08-24 12:42:05.932]\n[2018-08-24 12:42:05.933]Container exited with a non-zero exit code 143. [2018-08-24 12:42:05.933]\n",
> "containerExitType" : "NON_TRANSIENT"
> }
> [Master]: [LastCompletedTask]: [ContainerLocations]:
> ContainerLogHttpAddress: http://10.0.1.6:8042/node/containerlogs/container_1535113754342_0003_01_000002/admin/
> ContainerLogNetworkPath: 10.0.1.6:/var/lib/yarn/userlogs/application_1535113754342_0003/container_1535113754342_0003_01_000002
> ContainerCacheNetworkPath: 10.0.1.6:/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1535113754342_0003/container_1535113754342_0003_01_000002
> ________________________________________________________________________________________________________________________________________________________________________________________________________
> [ApplicationCompletionReason]: [Master]: FailedTaskCount 1 has reached MinFailedTaskCount 1.
>

**Comment by hao1939** [comment] 2018-08-24 13:51
It should related to YARN configuration below:
1. yarn.nodemanager.vmem-check-enabled: whether to check virtual memory.
2. yarn.scheduler.minimum-allocation-mb: minimum memory allocated for a scheduler. In this case, it's 1G.
3. yarn.nodemanager.vmem-pmem-ratio: virtual memory ratio, default is 2.1.

According to the log, the YARN container takes 5.8 GB of 2.1 GB, so it got killed by YARN.

> Current usage: 106.2 MB of 1 GB physical memory used; 5.8 GB of 2.1 GB virtual memory used. Killing container.

**Comment by mzmssg** [comment] 2018-08-28 03:09
This is a random failure, need more investigation.

**Comment by mzmssg** [comment] 2018-08-28 05:11
In failure cases, seems `hdfs getconf -confKey hadoop.tmp.dir` leads yarn container killed. But I can't reproduce it in other beds, a work around for Jenkins is raising job memory.

Success log:
```
++[03:34:05] ln -s /tmp/pai-root/log/application_1535425542470_0004/container_1535425542470_0004_01_000002/DockerContainerDebug.log /var/lib/yarn/userlogs/application_1535425542470_0004/container_1535425542470_0004_01_000002/DockerContainerDebug.log
+++[03:34:05] hdfs getconf -confKey hadoop.tmp.dir
++[03:34:05] hadoop_tmp_dir=/var/lib/hadoopdata
+++[03:34:05] cat /proc/self/cgroup
+++[03:34:05] head -n 1
```
Failure log:
```
++[04:34:04] ln -s /tmp/pai-root/log/application_1535425542470_0013/container_1535425542470_0013_01_000002/DockerContainerDebug.log /var/lib/yarn/userlogs/application_1535425542470_0013/container_1535425542470_0013_01_000002/DockerContainerDebug.log
+++[04:34:04] hdfs getconf -confKey hadoop.tmp.dir
+++[04:34:04] exit_handler
+++[04:34:04] local 'handler=Yarn container exit handler'
+++[04:34:04] debug_log 'Yarn container exit handler' 'EXIT signal received in yarn container, performing clean up action...'
```
Related code
https://github.com/Microsoft/pai/blob/36ec012c8396c1b6441182e894cb6743556e389a/rest-server/src/templates/yarnContainerScript.mustache#L231

**Comment by hao1939** [comment] 2018-08-30 04:35
#1148 is a workaround, still need to figure out the root cause.

**Comment by hao1939** [comment] 2018-09-04 10:55
Repeat again.
This time the cluster pipeline failed.
http://40.76.53.138:33080/blue/organizations/jenkins/pai/detail/qixcheng%2Frest-server%2Fdisable-quota-oom-retries/15/pipeline

**Comment by mzmssg** [comment] 2018-09-04 10:56
After replace `hdfs getconf` with hardcode, this error disappears

**Comment by mzmssg** [comment] 2018-10-16 11:56
Close it, please help reopen it if occurs again

**Closed by mzmssg** 2018-10-16 11:56 UTC
Labels: deployment, known issue

**Comment by hellocandy** [comment] 2019-02-18 00:57
We can reproduce the problem  now,

Start Time: 2019/2/13 下午3:43:31

Finish Time: 2019/2/13 下午3:44:47

Exit Diagnostics:


[ExitStatus]: CONTAINER_VIRTUAL_MEMORY_EXCEEDED
[ExitCode]: -103
[ExitDiagnostics]:
Container Killed since it exceeded the request virtual memory
[ExitType]: NON_TRANSIENT
________________________________________________________________________________________________________________________________________________________________________________________________________
[ExitCustomizedDiagnostics]:
[ExitCode]: -103
[ExitDiagnostics]:
[2019-02-13 07:44:33.796]Container [pid=188212,containerID=container_e04_1548839040935_6713_01_000002] is running beyond virtual memory limits. Current usage: 264.3 MB of 1 GB physical memory used; 2.8 GB of 2.1 GB virtual memory used. Killing container.
Dump of the process-tree for container_e04_1548839040935_6713_01_000002 :
|- PID PPID PGRPID SESSID CMD_NAME USER_MODE_TIME(MILLIS) SYSTEM_TIME(MILLIS) VMEM_USAGE(BYTES) RSSMEM_USAGE(PAGES) FULL_CMD_LINE
|- 188295 188212 188212 188212 (bash) 0 1 18620416 780 /bin/bash -c source YarnContainerScripts/0.sh 1>/var/lib/yarn/userlogs/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002/stdout 2>/var/lib/yarn/userlogs/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002/stderr 
|- 191569 188295 188212 188212 (java) 507 36 2981171200 65340 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Dproc_dfs -Xmx4096m -Djava.net.preferIPv4Stack=true -Dhadoop.log.dir=/var/log/hadoop/ -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/usr/local/hadoop -Dhadoop.id.str=admin -Dhadoop.root.logger=INFO,console -Djava.library.path=/usr/local/hadoop/lib/native -Dhadoop.policy.file=hadoop-policy.xml -Djava.net.preferIPv4Stack=true -Xmx1024m -Dhadoop.security.logger=INFO,console org.apache.hadoop.fs.FsShell -get hdfs://124.9.14.16:9000/Container/admin/admin~ff0fe9d7-6206-422d-b013-be5a99f78af1/DockerContainerScripts/0.sh tmp/pai-root/bootstrap/docker_bootstrap.sh 
|- 191533 188300 188212 188212 (sleep) 0 0 4481024 166 sleep 20 
|- 188212 188154 188212 188212 (bash) 3 0 18477056 712 bash -c cp -r /docker/* /usr/bin/ && cp /hadoop-configuration-for-jobs/* $HADOOP_CONF_DIR/ && bash "/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002/launch_container.sh" 
|- 188300 188295 188212 188212 (bash) 0 0 18550784 653 /bin/bash -c source YarnContainerScripts/0.sh 1>/var/lib/yarn/userlogs/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002/stdout 2>/var/lib/yarn/userlogs/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002/stderr 
[2019-02-13 07:44:33.796]
[2019-02-13 07:44:35.705]Container killed on request. Exit code is 143[2019-02-13 07:44:35.706]
[2019-02-13 07:44:35.707]Container exited with a non-zero exit code 143. [2019-02-13 07:44:35.707]

________________________________________________________________________________________________________________________________________________________________________________________________________
[ExitCustomizedDiagnostics]:

[jupyter]: [LastCompletedTask]: [TaskStatus]:
{
"taskIndex" : 0,
"taskRoleName" : "jupyter",
"taskState" : "TASK_COMPLETED",
"taskRetryPolicyState" : {
"retriedCount" : 0,
"succeededRetriedCount" : 0,
"transientNormalRetriedCount" : 0,
"transientConflictRetriedCount" : 0,
"nonTransientRetriedCount" : 0,
"unKnownRetriedCount" : 0
},
"taskCreatedTimestamp" : 1550043831619,
"taskCompletedTimestamp" : 1550043876019,
"taskServiceStatus" : {
"serviceVersion" : 0
},
"containerId" : "container_e04_1548839040935_6713_01_000002",
"containerHost" : "124.9.14.16",
"containerIp" : "124.9.14.16",
"containerPorts" : "jupyter:6038;http:6039;ssh:6040;",
"containerGpus" : 0,
"containerLogHttpAddress" : "http://124.9.14.16:8042/node/containerlogs/container_e04_1548839040935_6713_01_000002/admin/",
"containerConnectionLostCount" : 0,
"containerIsDecommissioning" : null,
"containerLaunchedTimestamp" : 1550043833071,
"containerCompletedTimestamp" : 1550043876015,
"containerExitCode" : -103,
"containerExitDiagnostics" : "[2019-02-13 07:44:33.796]Container [pid=188212,containerID=container_e04_1548839040935_6713_01_000002] is running beyond virtual memory limits. Current usage: 264.3 MB of 1 GB physical memory used; 2.8 GB of 2.1 GB virtual memory used. Killing container.\nDump of the process-tree for container_e04_1548839040935_6713_01_000002 :\n\t|- PID PPID PGRPID SESSID CMD_NAME USER_MODE_TIME(MILLIS) SYSTEM_TIME(MILLIS) VMEM_USAGE(BYTES) RSSMEM_USAGE(PAGES) FULL_CMD_LINE\n\t|- 188295 188212 188212 188212 (bash) 0 1 18620416 780 /bin/bash -c source YarnContainerScripts/0.sh 1>/var/lib/yarn/userlogs/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002/stdout 2>/var/lib/yarn/userlogs/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002/stderr \n\t|- 191569 188295 188212 188212 (java) 507 36 2981171200 65340 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Dproc_dfs -Xmx4096m -Djava.net.preferIPv4Stack=true -Dhadoop.log.dir=/var/log/hadoop/ -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/usr/local/hadoop -Dhadoop.id.str=admin -Dhadoop.root.logger=INFO,console -Djava.library.path=/usr/local/hadoop/lib/native -Dhadoop.policy.file=hadoop-policy.xml -Djava.net.preferIPv4Stack=true -Xmx1024m -Dhadoop.security.logger=INFO,console org.apache.hadoop.fs.FsShell -get hdfs://124.9.14.16:9000/Container/admin/admin~ff0fe9d7-6206-422d-b013-be5a99f78af1/DockerContainerScripts/0.sh tmp/pai-root/bootstrap/docker_bootstrap.sh \n\t|- 191533 188300 188212 188212 (sleep) 0 0 4481024 166 sleep 20 \n\t|- 188212 188154 188212 188212 (bash) 3 0 18477056 712 bash -c cp -r /docker/* /usr/bin/ && cp /hadoop-configuration-for-jobs/* $HADOOP_CONF_DIR/ && bash \"/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002/launch_container.sh\" \n\t|- 188300 188295 188212 188212 (bash) 0 0 18550784 653 /bin/bash -c source YarnContainerScripts/0.sh 1>/var/lib/yarn/userlogs/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002/stdout 2>/var/lib/yarn/userlogs/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002/stderr \n[2019-02-13 07:44:33.796]\n[2019-02-13 07:44:35.705]Container killed on request. Exit code is 143[2019-02-13 07:44:35.706]\n[2019-02-13 07:44:35.707]Container exited with a non-zero exit code 143. [2019-02-13 07:44:35.707]\n",
"containerExitType" : "NON_TRANSIENT"
}
[jupyter]: [LastCompletedTask]: [ContainerLocations]:
ContainerLogHttpAddress: http://124.9.14.16:8042/node/containerlogs/container_e04_1548839040935_6713_01_000002/admin/
ContainerLogNetworkPath: 124.9.14.16:/var/lib/yarn/userlogs/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002
ContainerCacheNetworkPath: 124.9.14.16:/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1548839040935_6713/container_e04_1548839040935_6713_01_000002
________________________________________________________________________________________________________________________________________________________________________________________________________
[ApplicationCompletionReason]: [jupyter]: FailedTaskCount 1 has reached MinFailedTaskCount 1.
