### ISSUE TITLE
Cannot launch job because of BarrierNotPassed

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4833] opened 2020-08-25 02:46 UTC
How to reproduce:

1. Disable hivedScheduler, and submit a lot of jobs (about 5 jobs/second)

2. Some jobs have the following error:

![image](https://user-images.githubusercontent.com/7499023/91116901-01692a00-e6c0-11ea-91f1-353e64097acb.png)

**Comment by fanyangCS** [comment] 2020-08-25 02:50
the job will retry automatically, right?

**Comment by hzy46** [comment] 2020-08-25 02:53
> the job will retry automatically, right?

Yes, but I noticed most jobs have this error, so the cluster was full of `WAITING` jobs

**Comment by yqwang-ms** [comment] 2020-08-25 03:02
Seems PodIP is not generated by kubelet in time. Can we investigate why?
BTW, why the timeout is so small : 2min (5:56 - 5:54)?  Is it due to the @hzy46 's log is truncated?

**Comment by yqwang-ms** [comment] 2020-08-26 02:13
Caused by long sync queuing in FC (and others, such as k8s controller manager), bound by k8s client side throttle.
Will tune k8s client side throttle to optimize the sync latency and throughput.

**Comment by yqwang-ms** [comment] 2020-09-02 07:52
Resolved by https://github.com/microsoft/pai/pull/4864

**Closed by yqwang-ms** 2020-09-02 07:52 UTC
