### ISSUE TITLE
如何在已经创建好的pai集群中新加入一台机器

### ISSUE THREAD

**Issue by qzwlinux** [Microsoft/pai#2369] opened 2019-03-21 07:58 UTC
**新的节点无法创建kubernetes环境**:

 python paictl.py cluster k8s-bootup -p ~/pai-config/

docker: Error response from daemon: Conflict. The container name "/kubelet" is already in use by container "e45ecf783f38bc6c8c9e13151128c2cb55ff5b741ce54b124e127446696d59e2". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Comment by fanyangCS** [comment] 2019-03-21 08:06
https://github.com/Microsoft/pai/blob/master/docs/paictl/paictl-manual.md#Machine_Add

**Comment by scarlett2018** [comment] 2019-03-22 10:54
@qzwlinux 您能按着Create Issue的Template把信息再丰富一下吗？谢谢。

Issue Template
Organization Name:

Short summary about the issue/question:
Brief what process you are following:

How to reproduce it:

OpenPAI Environment: Cluster, one master and two worker node.

OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Others:
Anything else we need to know:

**Comment by scarlett2018** [comment] 2019-03-22 10:55
Since Fan already provided the resolution, closing the issue. Please feel free to reopen it if you met problem with that document: https://github.com/Microsoft/pai/blob/master/docs/paictl/paictl-manual.md#Machine_Add

**Closed by scarlett2018** 2019-03-22 10:55 UTC
Labels: question, raised by customer
