### ISSUE TITLE
How to solve the problem "Failed to getApplicationProgress from RequestManager"?

### ISSUE THREAD

**Issue by Beyyes** [Microsoft/pai#1084] opened 2018-08-16 03:59 UTC
I submitted a job in pai, job config is shown as below
```
{
  "jobName": "tensorflow-hdfs-dist-sodex-1145",
  "image": "xxx/pai.run.tensorflow",
  "codeDir": "hdfs://10.190.148.73:9000//path/code/sodex/code",
  "killAllOnCompletedTaskNumber": 2,
  "retryCount": 0,
  "taskRoles": [
    {
      "name": "ps",
      "taskNumber": 2,
      "cpuNumber": 2,
      "memoryMB": 1024,
      "gpuNumber": 0,
      "command": "cd code && pip install -r requirements.txt && python darnn_dist.py --total_episodes=5 --train_output_dir=hdfs://10.190.148.73:9000/Output/admin/tensorflow-hdfs-dist-sodex-adcdfc95-5551-4697-ad7f-4e4f5366609a/ --ps_hosts=$PAI_TASK_ROLE_ps_HOST_LIST --worker_hosts=$PAI_TASK_ROLE_worker_HOST_LIST --job_name=ps --task_index=$PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX"
    },
    {
      "name": "worker",
      "taskNumber": 2,
      "cpuNumber": 4,
      "memoryMB": 2048,
      "gpuNumber": 0,
      "command": "cd code && pip install -r requirements.txt && python darnn_dist.py --total_episodes=5 --train_output_dir=hdfs://10.190.148.73:9000/Output/admin/tensorflow-hdfs-dist-sodex-adcdfc95-5551-4697-ad7f-4e4f5366609a/ --ps_hosts=$PAI_TASK_ROLE_ps_HOST_LIST --worker_hosts=$PAI_TASK_ROLE_worker_HOST_LIST --job_name=worker --task_index=$PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX"
    }
  ]
}
```

And some exceptions will be thrown when the job running
```
2018-08-16 03:46:18,299 DEBUG [main] org.apache.hadoop.security.SaslRpcClient: Received SASL message state: SUCCESS
token: "rspauth=6a3fc27276a4cc8f37797e1013b2bc08"

2018-08-16 03:46:18,352 INFO [main] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Running Framework [tensorflow-hdfs-dist-sodex-1145] in Queue [default]
2018-08-16 03:46:18,353 INFO [main] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Got 0 Containers from previous attempts
2018-08-16 03:46:18,359 DEBUG [main] com.microsoft.frameworklauncher.common.model.ResourceDescriptor: Converted ResourceDescriptor: [MemoryMB: [1048576] CpuNumber: [32] GpuNumber: [8] GpuAttribute: [0(0)] PortNumber: [0] PortRanges: [{}]] from Resource: <memory:1048576, vCores:32, GPUs:8, GPUAttribute:0, ports: null>
2018-08-16 03:46:18,363 DEBUG [main] org.apache.hadoop.service.AbstractService: Service: org.apache.hadoop.yarn.client.api.async.NMClientAsync entered state INITED
2018-08-16 03:46:18,363 INFO [main] org.apache.hadoop.yarn.client.api.async.impl.NMClientAsyncImpl: Upper bound of the thread pool size is 500
2018-08-16 03:46:18,363 DEBUG [main] org.apache.hadoop.service.AbstractService: Service: org.apache.hadoop.yarn.client.api.impl.NMClientImpl entered state INITED
2018-08-16 03:46:18,364 INFO [main] org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
2018-08-16 03:46:18,365 DEBUG [main] org.apache.hadoop.yarn.ipc.YarnRPC: Creating YarnRPC for org.apache.hadoop.yarn.ipc.HadoopYarnProtoRPC
2018-08-16 03:46:18,365 DEBUG [main] org.apache.hadoop.service.AbstractService: Service org.apache.hadoop.yarn.client.api.impl.NMClientImpl is started
2018-08-16 03:46:18,366 DEBUG [main] org.apache.hadoop.service.AbstractService: Service org.apache.hadoop.yarn.client.api.async.NMClientAsync is started
2018-08-16 03:46:18,369 DEBUG [main] org.apache.hadoop.service.AbstractService: Service: org.apache.hadoop.yarn.client.api.impl.YarnClientImpl entered state INITED
2018-08-16 03:46:18,370 DEBUG [main] org.apache.hadoop.service.AbstractService: Service: org.apache.hadoop.yarn.client.api.impl.AHSClientImpl entered state INITED
2018-08-16 03:46:18,380 DEBUG [main] org.apache.hadoop.service.AbstractService: Service: org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl entered state INITED
2018-08-16 03:46:18,390 DEBUG [main] org.apache.hadoop.security.ssl.FileBasedKeyStoresFactory: The property 'ssl.client.truststore.location' has not been set, no TrustStore will be loaded
2018-08-16 03:46:18,436 DEBUG [AMRM Callback Handler Thread] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Failed to getApplicationProgress from RequestManager.
Exception:
java.lang.NullPointerException
	at com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster.getApplicationProgress(ApplicationMaster.java:484)
	at com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster.getProgress(ApplicationMaster.java:1376)
	at com.microsoft.frameworklauncher.applicationmaster.RMClientCallbackHandler.getProgress(RMClientCallbackHandler.java:45)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:314)

2018-08-16 03:46:18,438 DEBUG [AMRM Callback Handler Thread] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Failed to getApplicationProgress from StatusManager. Return 0 Progress.
Exception:
java.lang.NullPointerException
	at com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster.getApplicationProgress(ApplicationMaster.java:484)
	at com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster.getProgress(ApplicationMaster.java:1376)
	at com.microsoft.frameworklauncher.applicationmaster.RMClientCallbackHandler.getProgress(RMClientCallbackHandler.java:45)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:314)
```

And the job will never stop, how to solve this problem?

The full logs is shown in this file: https://github.com/Beyyes/pai/blob/master/log.

**Comment by yqwang-ms** [comment] 2018-08-16 08:07
The exceptions are just DEBUG info, they are fine to have.
You can only check WARN and ERROR in future debugging.

For your job why never stop, I see WARNs related to "[worker][1]" is looping below logs:

> 2018-08-16 03:47:07,788 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [worker][1]: addContainerRequest: ContainerRequest cannot be satisfied within timeout 47s. Cancel it and Request again. ContainerRequest: [Priority: [2] Resource: [MemoryMB: [2048] CpuNumber: [4] GpuNumber: [0] GpuAttribute: [0(0)] PortNumber: [0] **PortRanges: [{[18912-18913]}]]** NodeLabel: [null] RelaxLocality: [true] HostNames: {} RackNames: {}]

So, this should be because your cluster do not have enough resource to satisfy:

> ContainerRequest: [Priority: [2] Resource: [MemoryMB: [2048] CpuNumber: [4] GpuNumber: [0] GpuAttribute: [0(0)] PortNumber: [0] **PortRanges: [{[18912-18913]}]]** NodeLabel: [null] RelaxLocality: [true] HostNames: {} RackNames: {}]

Seems you only have one node, and you enabled the "samePortsAllocation" (search it in the log).
So, if you have two different instance to ask for the same PortRanges, they cannot be allocated on the same node, but you only have one node.
So, the job keeps asking resource but never satisfied.

samePortsAllocation is default enabled in previous PAI releases, but we disabled it now.
See, https://github.com/Microsoft/pai/blob/90f1691551b00ffd317495d613ff6f9d450391c8/frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/TaskRolePlatformSpecificParametersDescriptor.java#L41

Solutions: 
Try to change above line to false, then rebuild and redeploy your PAI

@YitongFeng maybe we should create a hotfix about this for the latest release branch.

**Comment by YitongFeng** [comment] 2018-08-16 08:35
You can modify this line of code to "false" now, then rebuild and redeploy your PAI.
Our v0.7 release has fixed it, and will release soon.

**Comment by Beyyes** [comment] 2018-08-16 11:36
@yqwang-ms I use the latest dev-box, the code ```private Boolean samePortAllocation = false; ``` is in ```pai/frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/TaskRolePlatformSpecificParametersDescriptor.java```, I don't know where the ```samePortAllocation``` has been set ```true```.

**Comment by yqwang-ms** [comment] 2018-08-16 12:25
I am not familar with docker.io/openpai/dev-box.
@YitongFeng could you please help Beyyes to find where we set samePortAllocation to true?

**Comment by YitongFeng** [comment] 2018-08-17 11:48
@Beyyes There is src code in dev-box, it's at /pai/frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/TaskRolePlatformSpecificParametersDescriptor.java

**Comment by Beyyes** [comment] 2018-08-20 03:04
@YitongFeng 
But in my dev-box, the value of ```samePortAllocation``` is ```false``` just as the picture below shows.
![image](https://user-images.githubusercontent.com/6756545/44318432-6bfb8580-a468-11e8-8d21-4048d6417901.png)


And I don't know why in the logs the value of ```samePortsAllocation``` is true.
![image](https://user-images.githubusercontent.com/6756545/44318477-c09f0080-a468-11e8-8a16-725c65ea8357.png)

**Comment by YitongFeng** [comment] 2018-08-22 06:01
https://hub.docker.com/r/openpai/dev-box/tags/ The dev-box container was released a month before, which is in 0.6.1 version, I just checked it, this line is "true" in this version. Maybe you used `git pull` in dev-box, so your code has updated, now you can rebuild and redeploy your PAI, and check if it works.

**Comment by qinchen123** [comment] 2018-09-03 02:05
Checked the log: 
this issue is caused by the CPU resource not meet the request，not the Port:
There are only two nodes, each node has 4 CPUs, 
At first the application master used 1 cpu in 10.190.178.19, and there only 3 CPU left. 

when request two 4-CPU task, only the 10.190.150.223 successed, the task on 10.190.178.19 always fail becasue there only 3-CPU left.

**Comment by qinchen123** [comment] 2018-09-03 02:06
this failure-retry is by design, I suggest we can close this issue.

**Closed** 2018-09-03 03:46 UTC
