### ISSUE TITLE
command 'paiext.cluster.add' not found

### ISSUE THREAD

**Issue by Echohhhhhh** [microsoft/pai#3857] opened 2019-11-17 12:29 UTC
Issue Type: <b>Bug</b>

when I install openpai in server, when I run "pai: add pai cluster
", it wrong, command 'paiext.cluster.add' not found

Extension version: 0.2.2
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-154-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: gpu-test|
|OS|Linux x64 4.4.0-154-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 2299)|
|Memory (System)|125.80GB (3.26GB free)|
|VM|0%|
</details>

**Comment by feidieufo** [comment] 2019-11-24 14:16
> Issue Type: Bug
> 
> when I install openpai in server, when I run "pai: add pai cluster
> ", it wrong, command 'paiext.cluster.add' not found
> 
> Extension version: 0.2.2
> VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
> OS version: Windows_NT x64 10.0.18362
> Remote OS version: Linux x64 4.4.0-154-generic
> 
> System Info

I try to downgrade to 0.2.1, then it's fine

**Comment by yiyione** [comment] 2019-11-25 07:02
Hi @Echohhhhhh and @feidieufo , I can't repro this bug, can you tell me your OpenPAI cluster version?

**Comment by feidieufo** [comment] 2019-11-25 07:09
> Hi @Echohhhhhh and @feidieufo , I can't repro this bug, can you tell me your OpenPAI cluster version?

0.14

**Comment by yiyione** [comment] 2019-11-25 08:27
@feidieufo  The error throw immediately after you click the `PAI: Add PAI Cluster`? Or after enter the host name?

**Comment by feidieufo** [comment] 2019-11-25 08:29
> @feidieufo The error throw immediately after you click the `PAI: Add PAI Cluster`? Or after enter the host name?

immediately

**Comment by yiyione** [comment] 2019-11-28 07:50
I still can't reproduce the bug, my suggestion is reinstall the `OpenPAI VS Code Client` extension, and make sure the VS Code version is higher than `1.39.2`.
If anyone has an idea about how to repro it, please let me know, thanks.

**Comment by DeepDarkOdyssey** [comment] 2019-12-13 07:52
Same issue here, downgrade to 0.2.1 solve the problem

**Comment by shiyemin** [comment] 2019-12-24 04:33
> I still can't reproduce the bug, my suggestion is reinstall the `OpenPAI VS Code Client` extension, and make sure the VS Code version is higher than `1.39.2`.
> If anyone has an idea about how to repro it, please let me know, thanks.

Maybe this can help you reproduce the bug.
1. Install Remote Development plugin in VS Code;
2. Connect to a remote ssh server;
3. Try enable OpenPAI VS Code Client and run "Add PAI Cluster";
4. Failed.

**Comment by shiyemin** [comment] 2019-12-26 02:27
@yiyione Hi, can you take a look at my comment? It should be able to reproduce the bug. After update to 0.2.3, the bug still exists.

**Comment by yiyione** [comment] 2020-02-27 16:56
@shiyemin Hi, sorry for the late reply, looks like some case sensitivity problem cause the Extension active failed.
There's a workaround for it:
1. In the remote server, goto location `~/.vscode-server/extensions/openpaivscodeclient.pai-vscode-0.2.3/out/pai`
2. rename the file `AzureADLogin.js` to `azureADLogin.js`
3. reload the remote VSCode window.

Thanks

**Comment by scarlett2018** [comment] 2020-04-17 04:20
> @shiyemin Hi, sorry for the late reply, looks like some case sensitivity problem cause the Extension active failed.
> There's a workaround for it:
> 
> 1. In the remote server, goto location `~/.vscode-server/extensions/openpaivscodeclient.pai-vscode-0.2.3/out/pai`
> 2. rename the file `AzureADLogin.js` to `azureADLogin.js`
> 3. reload the remote VSCode window.
> 
> This case sensitivity problem has been fixed in master branch, and this bug should be resolve in next release.
> Thanks

@yiyione had this fix released?

**Comment by scarlett2018** [comment] 2020-06-01 07:35
fixed in v0.17

**Closed by scarlett2018** 2020-06-01 07:35 UTC
Labels: bug, raised by customer, vs code extension
