### ISSUE TITLE
job cannot use the same name, even from different user

### ISSUE THREAD

**Issue by fanyangCS** [Microsoft/pai#130] opened 2017-12-22 10:04 UTC

**Comment by abuccts** [comment] 2017-12-22 11:11
we need to modify launcher path on hdfs and zk from `/Launcher/FrameworkName` to `/Launcher/UserName/FrameworkName` @yqwang-ms

**Comment by yqwang-ms** [comment] 2017-12-22 12:46
By design we ONLY use FrameworkName to identify Framework, i.e. FrameworkName is the key/id for the Framework. It helps to achieve all APIs are IDEMPOTENT and STATELESS, thus Work Preserving Client Restart.

If we add user into the key:
1. We need to change a lot codes.
2. You still cannot avoid the same name within the same user.

So, suggest RestServer(i.e. Launcher's clients) to:
1. set the FrameworkName to be UserName_JobName. 
2. Or, if you can ensure you are submitting a new job instead of updating a job or retry the submission, you can generate a unique/un-conflict FrameworkName for user.

**Comment by fanyangCS** [comment] 2017-12-22 13:02
I like the first option: username_jobname

**Comment by abuccts** [comment] 2017-12-22 13:05
We also need to restore the concatenated string to show the original JobName on webportal correctly, right?

**Comment by fanyangCS** [comment] 2017-12-22 23:59
Yes

**Comment by hao1939** [comment] 2018-07-09 02:35
Duplicate of #562

**Closed by hao1939** 2018-07-09 02:35 UTC
Labels: duplicate, framework-launcher, restserver
