### ISSUE TITLE
[Feedback v0.14.0]standardout does not print out anything

### ISSUE THREAD

**Issue by firedie** [microsoft/pai#4051] opened 2019-12-23 09:05 UTC
I wish to train a pytorch model on PAI, while training I am using tqdm to print out the progress as well as a print function to print out loss etc. However, nothing will be print out on stdout until it reach about 30mins mark. Moreover, the progress bar of tqdm will be print out on std err. Here is the structure of my code:
 ...
`
for epoch in range(100):

    train_tqdm = tqdm

    for i, data in tqdm:

    TRAINING

    print(...)
`
resulting:
![image](https://user-images.githubusercontent.com/18274020/71347813-18da9b00-25a6-11ea-9617-a8cccd59502a.png)
nothing been print out in standard out
![image](https://user-images.githubusercontent.com/18274020/71347834-2bed6b00-25a6-11ea-929c-c3a9af84f1b4.png)
but something been print out in standard error.
Moreover, if I wait another 30 minutes, message will pop out in stdout
![image](https://user-images.githubusercontent.com/18274020/71347902-53443800-25a6-11ea-8249-d2fe5d3101d5.png)
Anyone know why? CHEERS

**Comment by Binyang2014** [comment] 2019-12-25 02:48
@firedie Can you add `force flush` in your source code and check again? Please refer to https://stackoverflow.com/questions/230751/how-to-flush-output-of-print-function
Maybe caused by io buffer

**Comment by firedie** [comment] 2020-01-02 10:13
Cheers the force flush solved my printing problem
How about the  tqdm progress meter in the standard error, can you help fix that?

**Comment by Binyang2014** [comment] 2020-02-27 13:18
Hi @firedie Sorry for late reply...
For the tqdm issue, please return to https://github.com/tqdm/tqdm#parameters.
You can point the `file` parameter to `sys.stdout` if you want to print to stdout. The default value is `stderr`

**Comment by scarlett2018** [comment] 2020-04-17 06:15
Closing the issue as the 2nd question had been answered as well. Thanks @Binyang2014 and @firedie

**Closed by scarlett2018** 2020-04-17 06:15 UTC
Labels: FAQ, PAI-Usage, log, raised by customer
