### ISSUE TITLE
`/paictl.py cluster k8s-bootup -p /cluster-configuration` randomly failed

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1153] opened 2018-08-27 04:15 UTC
The k8s-bootup randomly failed because of `kube-proxy`.

> ...
> 2018-08-27 04:10:31,663 [INFO] - k8sPaiLibrary.maintainlib.kubectl_install : Generate the configuation file of kubectl.
> NAME       STATUS     ROLES     AGE       VERSION
> 10.0.1.5   Ready      <none>    21s       v1.9.4
> 10.0.1.7   NotReady   <none>    4s        v1.9.4
> 10.0.1.8   Ready      <none>    20s       v1.9.4
> 2018-08-27 04:10:35,939 [INFO] - k8sPaiLibrary.maintainlib.kubectl_install : Successfully install kubectl and configure it!
> 2018-08-27 04:10:35,939 [INFO] - k8sPaiLibrary.maintainlib.deploy : Create kube-proxy daemon for kuberentes cluster.
> error: unable to recognize "kube-proxy.yaml": no matches for kind "DaemonSet" in version "apps/v1"
> 2018-08-27 04:10:36,241 [ERROR] - k8sPaiLibrary.maintainlib.common : Failed to create kube-proxy

**Comment by YitongFeng** [comment] 2018-08-27 09:26
@fanyangCS OK, others are closed but can't be deleted. Reference of the similar issues is for easy tracking.

**Comment by mzmssg** [comment] 2018-08-27 13:14
update in #1166

**Comment by YitongFeng** [comment] 2018-08-28 02:10
For no matches for kind "DaemonSet" in version "apps/v1", it maybe the k8s API version's problem. 
Our k8s version is 1.9, refer to [k8s 1.9 API docs](https://v1-9.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#daemonset-v1-apps), it shows that v1.9 DaemontSet support "apps/v1", "apps/v1beta1" and "apps/v1beta2". The "beta" is testing version, if this version runs well k8s group will upgrade it to "apps/v1" and marked as stable version.

Our single-node k8s version is 1.9.4, maybe can't totally support the stable version "apps/v1", #1126 change the version to 1.9.9, and have not appear the error now. Or you can use "apps/v1beta1" and "apps/v1beta2" in your daemonset yaml file.

**Comment by hao1939** [comment] 2018-08-28 11:32
More details:

- In the dev-box which raise `error: unable to recognize "kube-proxy.yaml": no matches for kind "DaemonSet" in version "apps/v1beta2"`:
> root@infra-03:/# kubectl version
> Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
> root@infra-03:/# kubectl get daemonset
> No resources found.


- The dev-box which is fine:
> root@infra-03:/# kubectl version
> Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
> root@infra-03:/# kubectl get daemonset
> NAME                  DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR           AGE
> drivers-one-shot      3         3         3         3            3           machinetype=gpu         18m
> hadoop-data-node-ds   2         2         0         2            0           hadoop-data-node=true   43s
> hadoop-name-node-ds   1         1         1         1            1           hadoop-name-node=true   1m
> zookeeper-ds          1         1         1         1            1           zookeeper=true          20m

**Comment by hao1939** [comment] 2018-08-28 11:59
Hi @YitongFeng ,

Can we check `kubectl api-resources |grep DaemonSet` before install any DaemonSet?
Suspect it's a race condition problem: when trying to create the DaemonSet, the api-server is not fully ready.

**Comment by YitongFeng** [comment] 2018-08-28 13:51
It's maybe etcd's problem.
When the error occurs, etcd log shows endless warning:
![image](https://user-images.githubusercontent.com/11583225/44726194-ce5c2200-ab09-11e8-8fa7-10f77f788684.png)

When deployed successfully, the etcd log is clean:
![image](https://user-images.githubusercontent.com/11583225/44726323-111dfa00-ab0a-11e8-82a6-28c459312d9a.png)

When deploying a pod, the api-servier will register ResourceGroup and ResourceVersion as RestAPI, and will communicate with etcd. So the etcd timeout may cause the deploy process can't find the Resource Type.

The possible cause of etcd timeout:
https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-apply-entries-took-too-long-mean

**Comment by sterowang** [comment] 2018-08-29 02:05
Is this possibly caused too small VMs for qualification bed? One possible action is we increase the VMs size on qualification bed to see is there any improvements.

**Comment by YitongFeng** [comment] 2018-08-29 02:41
@sterowang low disk IO is the usually cause.
https://github.com/etcd-io/etcd/blob/master/Documentation/tuning.md#disk may help to tune etcd. + @hao1939 help to test later.

**Comment by hao1939** [comment] 2018-08-29 04:05
Try to use ramdisk for etcd, it works fine.
`sudo mount -t tmpfs -o size=2048M tmpfs /var/etcd`

**Comment by fanyangCS** [comment] 2018-08-29 04:15
If this is the disk I/O issue, it could very likely happen in other bed as well. The short-term solution could be to add some retry to every etcd operation (don't forget to add some random backoff between retries). Long term, we could add an option to support etcd deployment to a disk other than OS disk. I do not prefer ramdisk as it is not a realistic real-world deployment environment

**Comment by YitongFeng** [comment] 2018-08-30 03:57
Maybe we found the root cause:

The proxy was create at 3:31:23:
![image](https://user-images.githubusercontent.com/11583225/44828573-2f3f4380-ac4b-11e8-9b23-53f8c0eda0f9.png)

But the controllermanager's log shows daemonset resource is registerd at 3:31:24:
![image](https://user-images.githubusercontent.com/11583225/44828694-aecd1280-ac4b-11e8-925c-af33cee67da9.png)

So it can't find the daemonset resources at that time.

We will fix it in our next serveral PRs.

**Comment by hao1939** [comment] 2018-08-30 05:30
We get some output from `kubectl api-resources`:
http://40.76.53.138:33080/blue/organizations/jenkins/pai/detail/hao%2Ftest_k8sbootup/4/pipeline/45

> NAME                     SHORTNAMES   APIGROUP                 NAMESPACED   KIND
> bindings                                                       true         Binding
> componentstatuses        cs                                    false        ComponentStatus
> configmaps               cm                                    true         ConfigMap
> endpoints                ep                                    true         Endpoints
> events                   ev                                    true         Event
> limitranges              limits                                true         LimitRange
> namespaces               ns                                    false        Namespace
> nodes                    no                                    false        Node
> persistentvolumeclaims   pvc                                   true         PersistentVolumeClaim
> persistentvolumes        pv                                    false        PersistentVolume
> pods                     po                                    true         Pod
> podtemplates                                                   true         PodTemplate
> replicationcontrollers   rc                                    true         ReplicationController
> resourcequotas           quota                                 true         ResourceQuota
> secrets                                                        true         Secret
> serviceaccounts          sa                                    true         ServiceAccount
> services                 svc                                   true         Service
> apiservices                           apiregistration.k8s.io   false        APIService
> 2018-08-30 05:24:25,572 [INFO] - k8sPaiLibrary.maintainlib.deploy : Create kube-proxy daemon for kuberentes cluster.
> error: unable to recognize "kube-proxy.yaml": no matches for kind "DaemonSet" in version "apps/v1"
> 2018-08-30 05:24:25,882 [ERROR] - k8sPaiLibrary.maintainlib.common : Failed to create kube-proxy

**Closed** 2018-08-31 09:19 UTC
Labels: deployment, known issue
