### ISSUE TITLE
Job Errors on OpenStack Private Cloud (PAI v0.14.0)

### ISSUE THREAD

**Issue by liuc-shaiic** [microsoft/pai#4163] opened 2020-01-23 01:46 UTC
**Shaiic**:

**Error message of "1514 Illegal instruction (core dumped)" while running a "hello world" job with gpu: 0 using PAI v0.14.0**:

**I‘m running a "Hello World" job(see below) with PAI v0.14.0, and I get an error message of "1514 Illegal instruction (core dumped)"

Docker image: openpai/tensorflow-py36-cpu
Command:
pip3 install contextlib2
apt update
apt install -y git
git clone https://github.com/tensorflow/models
cd models/research/slim
pip3 install contextlib2 Pillow
python download_and_convert_data.py --dataset_name=cifar10 --dataset_dir=/tmp/data
python train_image_classifier.py --dataset_name=cifar10 --dataset_dir=/tmp/data --max_number_of_steps=1000

**:

**
Process to reproduce:
1. Open "Platform for AI" GUI and access "submit job" menu
2. Fill in the following commands in "Command" textfield:
apt update
apt install -y git
git clone https://github.com/tensorflow/models
cd models/research/slim
pip3 uninstall tensorflow
pip3 install contextlib2 Pillow tensorflow==1.14
python download_and_convert_data.py --dataset_name=cifar10 --dataset_dir=/tmp/data
python train_image_classifier.py --dataset_name=cifar10 --dataset_dir=/tmp/data --max_number_of_steps=1000 --clone_on_cpu=True

3. Set "GPU count" to "0" in the "Resources per instance" filed
4. Toggle "Custom" in the "Docker image" field and enter "openpai/tensorflow-py36-cpu" in the text
box

5. Click "Submit" button, and after a while the error message is shown:

Exit Code:
132
Exit Type:
USER_FAILURE
Exit Reason:
Container killed by OS Signal: SIGILL
Exit Solutions:
Check container log and fix your program bug

6. Click "stderr“， you'll see the message below:
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
Cloning into 'models'...
Checking out files:  36% (1180/3194)   
Checking out files:  37% (1182/3194)   
Checking out files:  38% (1214/3194)   
Checking out files:  39% (1246/3194)   
Checking out files:  40% (1278/3194)   
Checking out files:  41% (1310/3194)   
Checking out files:  42% (1342/3194)   
Checking out files:  43% (1374/3194)   
Checking out files:  44% (1406/3194)   
Checking out files:  45% (1438/3194)   
Checking out files:  46% (1470/3194)   
Checking out files:  47% (1502/3194)   
Checking out files:  48% (1534/3194)   
Checking out files:  49% (1566/3194)   
Checking out files:  50% (1597/3194)   
Checking out files:  51% (1629/3194)   
Checking out files:  52% (1661/3194)   
Checking out files:  53% (1693/3194)   
Checking out files:  54% (1725/3194)   
Checking out files:  55% (1757/3194)   
Checking out files:  56% (1789/3194)   
Checking out files:  57% (1821/3194)   
Checking out files:  58% (1853/3194)   
Checking out files:  59% (1885/3194)   
Checking out files:  60% (1917/3194)   
Checking out files:  61% (1949/3194)   
Checking out files:  61% (1979/3194)   
Checking out files:  62% (1981/3194)   
Checking out files:  63% (2013/3194)   
Checking out files:  64% (2045/3194)   
Checking out files:  65% (2077/3194)   
Checking out files:  66% (2109/3194)   
Checking out files:  67% (2140/3194)   
Checking out files:  68% (2172/3194)   
Checking out files:  69% (2204/3194)   
Checking out files:  70% (2236/3194)   
Checking out files:  71% (2268/3194)   
Checking out files:  72% (2300/3194)   
Checking out files:  73% (2332/3194)   
Checking out files:  74% (2364/3194)   
Checking out files:  75% (2396/3194)   
Checking out files:  76% (2428/3194)   
Checking out files:  77% (2460/3194)   
Checking out files:  78% (2492/3194)   
Checking out files:  79% (2524/3194)   
Checking out files:  80% (2556/3194)   
Checking out files:  81% (2588/3194)   
Checking out files:  82% (2620/3194)   
Checking out files:  83% (2652/3194)   
Checking out files:  83% (2677/3194)   
Checking out files:  84% (2683/3194)   
Checking out files:  85% (2715/3194)   
Checking out files:  86% (2747/3194)   
Checking out files:  87% (2779/3194)   
Checking out files:  88% (2811/3194)   
Checking out files:  89% (2843/3194)   
Checking out files:  90% (2875/3194)   
Checking out files:  91% (2907/3194)   
Checking out files:  92% (2939/3194)   
Checking out files:  93% (2971/3194)   
Checking out files:  94% (3003/3194)   
Checking out files:  95% (3035/3194)   
Checking out files:  96% (3067/3194)   
Checking out files:  97% (3099/3194)   
Checking out files:  98% (3131/3194)   
Checking out files:  99% (3163/3194)   
Checking out files: 100% (3194/3194)   
Checking out files: 100% (3194/3194), done.
WARNING: Skipping tensorflow as it is not installed.
WARNING: You are using pip version 19.2.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/pai/bootstrap/docker_bootstrap.sh: line 206:   750 Illegal instruction     (core dumped) python download_and_convert_data.py --dataset_name=cifar10 --dataset_dir=/tmp/data

**:

**OpenPAI Environment**:
- OpenPAI version: v0.14.0
- Cloud provider or hardware configuration: Yidian Cloud powered by i-stack Cloud OS (An OpenStack Private Cloud)
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):Linux liuc01-wushan 4.4.0-170-generic #199-Ubuntu SMP Thu Nov 14 01:45:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 16 cores cpu/128g memory/100g disk
- Others:

**Anything else we need to know**:

**Comment by abuccts** [comment] 2020-02-06 03:48
Hi, according to your log
```
Checking out files: 100% (3194/3194), done.
WARNING: Skipping tensorflow as it is not installed.
WARNING: You are using pip version 19.2.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/pai/bootstrap/docker_bootstrap.sh: line 206: 750 Illegal instruction (core dumped) python download_and_convert_data.py --dataset_name=cifar10 --dataset_dir=/tmp/data
```
seems it does not execute the pip install part in commands:
```
pip3 uninstall tensorflow
pip3 install contextlib2 Pillow tensorflow==1.14
```

Your reproduction commands work for me,
```sh
apt update
apt install -y git
git clone https://github.com/tensorflow/models
cd models/research/slim
pip3 uninstall tensorflow
pip3 install contextlib2 Pillow tensorflow==1.14
python download_and_convert_data.py --dataset_name=cifar10 --dataset_dir=/tmp/data
python train_image_classifier.py --dataset_name=cifar10 --dataset_dir=/tmp/data --max_number_of_steps=1000 --clone_on_cpu=True
```
could you pls check `pip install` works fine in your environment, e.g. network?

**Comment by liuc-shaiic** [comment] 2020-02-12 03:10
Thx Abuttcs for reply! I login to the container and "pip install" command works fine. I add "pip install --upgrade pip"  and remoe "pip3 uninstall tensorflow" in the "Command" textfield, and **the warning message has gone away but the same error still exists.**

Given below is the current "Command":
> apt update
> apt install -y git
> git clone https://github.com/tensorflow/models
> cd models/research/slim
> pip install --upgrade pip
> pip3 install contextlib2 Pillow tensorflow==1.14
> python download_and_convert_data.py --dataset_name=cifar10 --dataset_dir=/tmp/data
> python train_image_classifier.py --dataset_name=cifar10 --dataset_dir=/tmp/data --max_number_of_steps=1000 --clone_on_cpu=True

Given below is the Stdout log:
> B]
> Fetched 3912 kB in 4s (963 kB/s)
> (Reading database ... 
> (Reading database ... 5%
> (Reading database ... 10%
> (Reading database ... 15%
> (Reading database ... 20%
> (Reading database ... 25%
> (Reading database ... 30%
> (Reading database ... 35%
> (Reading database ... 40%
> (Reading database ... 45%
> (Reading database ... 50%
> (Reading database ... 55%
> (Reading database ... 60%
> (Reading database ... 65%
> (Reading database ... 70%
> (Reading database ... 75%
> (Reading database ... 80%
> (Reading database ... 85%
> (Reading database ... 90%
> (Reading database ... 95%
> (Reading database ... 100%
> (Reading database ... 20949 files and directories currently installed.)
> Preparing to unpack .../git_1%3a2.17.1-1ubuntu0.5_amd64.deb ...
> Unpacking git (1:2.17.1-1ubuntu0.5) over (1:2.17.1-1ubuntu0.4) ...
> Setting up git (1:2.17.1-1ubuntu0.5) ...
> Collecting pip
>   Downloading https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl (1.4MB)
> Installing collected packages: pip
>   Found existing installation: pip 19.2.2
>     Uninstalling pip-19.2.2:
>       Successfully uninstalled pip-19.2.2
> Successfully installed pip-20.0.2
> Collecting contextlib2
>   Downloading contextlib2-0.6.0.post1-py2.py3-none-any.whl (9.8 kB)
> Collecting Pillow
>   Downloading Pillow-7.0.0-cp36-cp36m-manylinux1_x86_64.whl (2.1 MB)
> Collecting tensorflow==1.14
>   Downloading tensorflow-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (109.2 MB)
> Requirement already satisfied: google-pasta>=0.1.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (0.1.7)
> Requirement already satisfied: gast>=0.2.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (0.2.2)
> Collecting tensorflow-estimator<1.15.0rc0,>=1.14.0rc0
>   Downloading tensorflow_estimator-1.14.0-py2.py3-none-any.whl (488 kB)
> Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.12.0)
> Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.11.2)
> Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.22.0)
> Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.1.0)
> Collecting tensorboard<1.15.0,>=1.14.0
>   Downloading tensorboard-1.14.0-py3-none-any.whl (3.1 MB)
> Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (3.9.1)
> Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.1.0)
> Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (0.7.1)
> Requirement already satisfied: numpy<2.0,>=1.14.5 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.17.0)
> Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (0.33.4)
> Requirement already satisfied: keras-applications>=1.0.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.0.8)
> Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (0.8.0)
> Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14) (41.1.0)
> Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14) (3.1.1)
> Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14) (0.15.5)
> Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras-applications>=1.0.6->tensorflow==1.14) (2.9.0)
> Installing collected packages: contextlib2, Pillow, tensorflow-estimator, tensorboard, tensorflow
> Successfully installed Pillow-7.0.0 contextlib2-0.6.0.post1 tensorboard-1.14.0 tensorflow-1.14.0 tensorflow-estimator-1.14.0

**it shows that the network works fine.**

Given below is the Stderr message:


> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> debconf: unable to initialize frontend: Dialog
> debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
> debconf: falling back to frontend: Readline
> Cloning into 'models'...
> Checking out files:  60% (1830/3015)   
> Checking out files:  61% (1840/3015)   
> Checking out files:  62% (1870/3015)   
> Checking out files:  63% (1900/3015)   
> Checking out files:  64% (1930/3015)   
> Checking out files:  65% (1960/3015)   
> Checking out files:  66% (1990/3015)   
> Checking out files:  67% (2021/3015)   
> Checking out files:  68% (2051/3015)   
> Checking out files:  69% (2081/3015)   
> Checking out files:  70% (2111/3015)   
> Checking out files:  71% (2141/3015)   
> Checking out files:  72% (2171/3015)   
> Checking out files:  73% (2201/3015)   
> Checking out files:  74% (2232/3015)   
> Checking out files:  75% (2262/3015)   
> Checking out files:  76% (2292/3015)   
> Checking out files:  77% (2322/3015)   
> Checking out files:  78% (2352/3015)   
> Checking out files:  79% (2382/3015)   
> Checking out files:  80% (2412/3015)   
> Checking out files:  80% (2440/3015)   
> Checking out files:  81% (2443/3015)   
> Checking out files:  82% (2473/3015)   
> Checking out files:  83% (2503/3015)   
> Checking out files:  84% (2533/3015)   
> Checking out files:  85% (2563/3015)   
> Checking out files:  86% (2593/3015)   
> Checking out files:  87% (2624/3015)   
> Checking out files:  88% (2654/3015)   
> Checking out files:  89% (2684/3015)   
> Checking out files:  90% (2714/3015)   
> Checking out files:  90% (2727/3015)   
> Checking out files:  91% (2744/3015)   
> Checking out files:  92% (2774/3015)   
> Checking out files:  93% (2804/3015)   
> Checking out files:  94% (2835/3015)   
> Checking out files:  95% (2865/3015)   
> Checking out files:  96% (2895/3015)   
> Checking out files:  97% (2925/3015)   
> Checking out files:  98% (2955/3015)   
> Checking out files:  99% (2985/3015)   
> Checking out files: 100% (3015/3015)   
> Checking out files: 100% (3015/3015), done.
> /pai/bootstrap/docker_bootstrap.sh: line 206:   691 Illegal instruction     (core dumped) python download_and_convert_data.py --dataset_name=cifar10 --dataset_dir=/tmp/data
> 
>

**Comment by abuccts** [comment] 2020-02-12 06:37
<details>
<summary>Here's the config I used to reproduce your issue.</summary>
<pre>
protocolVersion: 2
name: test
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: openpai/tensorflow-py36-cpu
    name: docker_image_0
taskRoles:
  test:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: 1
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 0
      cpu: 4
      memoryMB: 8192
    commands:
      - apt update
      - apt install -y git
      - 'git clone https://github.com/tensorflow/models'
      - cd models/research/slim
      - pip3 install contextlib2 Pillow tensorflow==1.14
      - >-
        python download_and_convert_data.py --dataset_name=cifar10
        --dataset_dir=/tmp/data
      - >-
        python train_image_classifier.py --dataset_name=cifar10
        --dataset_dir=/tmp/data --max_number_of_steps=1000 --clone_on_cpu=True
    taskRetryCount: 0
defaults:
  virtualCluster: default
</pre>
</details>

How much memory did you specify for the job? 4GB maybe not enough.
And could you also paste the logs by clicking "View Exit Diagnostics" in job detail page?

**Comment by liuc-shaiic** [comment] 2020-02-12 12:07
I use a 12GB memory but still the error occurs.

Given below are the logs of "View Exit Diagnostics":

> [Exit Trigger Info]
> 
> ExitTriggerMessage: FailedTaskCount 1 has reached MinFailedTaskCount 1 in TaskRole [Task_role_1]
> ExitTriggerTaskRole: Task_role_1
> ExitTriggerTaskIndex: 0
> UserExitCode: 132
> 
> --------------------------------------------------------------------------------
> 
> [Exit Spec]
> 
> code: 132
> phrase: CONTAINER_KILLED_BY_SIGILL
> issuer: USER_CONTAINER
> causer: USER_CONTAINER
> type: USER_FAILURE
> stage: RUNNING
> behavior: NON_TRANSIENT
> reaction: NEVER_RETRY
> reason: 'Container killed by OS Signal: SIGILL'
> repro:
>   - >-
>     User program executes an illegal, malformed, unknown, or privileged machine
>     instruction
> solution:
>   - Check container log and fix your program bug
> 
> 
> --------------------------------------------------------------------------------
> 
> [Exit Diagnostics]
> 
> [2020-02-12 11:43:23.226]Exception from container-launch: 
> ExitCodeException exitCode=132: 
> 	at org.apache.hadoop.util.Shell.runCommand(Shell.java:998)
> 	at org.apache.hadoop.util.Shell.run(Shell.java:884)
> 	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1216)
> 	at org.apache.hadoop.yarn.server.nodemanager.DockerContainerExecutor.launchContainer(DockerContainerExecutor.java:312)
> 	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.launchContainer(ContainerLaunch.java:443)
> 	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:294)
> 	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:92)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> [2020-02-12 11:43:23.226]
> [2020-02-12 11:43:23.228]Container exited with a non-zero exit code 132. Last 40960 bytes of runtime.pai.agg.error :
> [PAI_RUNTIME_ERROR_START]
> exitcode: 132
> trigger: caughtSignal
> reason: |
>   
> solution: |
>   
> originalUserExitCode: 132
> dockerStatus: 
> caughtSignal: SIGILL
> caughtException:
> matchedUserLogString:
> errorLogs:
>   user: |
>     f/FrontEnd/Dialog.pm line 76, <> line 1.)
>     debconf: falling back to frontend: Readline
>     Cloning into 'models'...
>     Checking out files: 60% (1801/2986) Checking out files: 61% (1822/2986) Checking out files: 62% (1852/2986) Checking out files: 63% (1882/2986) Checking out files: 64% (1912/2986) Checking out files: 65% (1941/2986) Checking out files: 66% (1971/2986) Checking out files: 67% (2001/2986) Checking out files: 68% (2031/2986) Checking out files: 69% (2061/2986) Checking out files: 70% (2091/2986) Checking out files: 71% (2121/2986) Checking out files: 72% (2150/2986) Checking out files: 73% (2180/2986) Checking out files: 74% (2210/2986) Checking out files: 75% (2240/2986) Checking out files: 76% (2270/2986) Checking out files: 77% (2300/2986) Checking out files: 78% (2330/2986) Checking out files: 79% (2359/2986) Checking out files: 80% (2389/2986) Checking out files: 81% (2419/2986) Checking out files: 82% (2449/2986) Checking out files: 83% (2479/2986) Checking out files: 83% (2492/2986) Checking out files: 84% (2509/2986) Checking out files: 85% (2539/2986) Checking out files: 86% (2568/2986) Checking out files: 87% (2598/2986) Checking out files: 88% (2628/2986) Checking out files: 89% (2658/2986) Checking out files: 90% (2688/2986) Checking out files: 91% (2718/2986) Checking out files: 92% (2748/2986) Checking out files: 93% (2777/2986) Checking out files: 94% (2807/2986) Checking out files: 94% (2827/2986) Checking out files: 95% (2837/2986) Checking out files: 96% (2867/2986) Checking out files: 97% (2897/2986) Checking out files: 98% (2927/2986) Checking out files: 99% (2957/2986) Checking out files: 100% (2986/2986) Checking out files: 100% (2986/2986), done.
>     /pai/bootstrap/docker_bootstrap.sh: line 206: 801 Illegal instruction (core dumped) python download_and_convert_data.py --dataset_name=cifar10 --dataset_dir=/tmp/data
>   runtime: |
>     1581507801 ERROR REASON "User process exited with code: 132"
>     WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
>     1581507802 INFO USER_EXIT_CODE 132
>     1581507802 ERROR MESSAGE Container exited because of the OS signal
>     1581507802 ERROR RECEIVE_SIGNAL "SIGILL"
>   diskCleaner: |
> [PAI_RUNTIME_ERROR_END]
> 
> [2020-02-12 11:43:23.228]

Here's the job config

> protocolVersion: 2
> name: admin_1581505909356
> type: job
> jobRetryCount: 0
> prerequisites:
>   - type: dockerimage
>     uri: openpai/tensorflow-py36-cpu
>     name: docker_image_0
> taskRoles:
>   Task_role_1:
>     instances: 1
>     completion:
>       minFailedInstances: 1
>       minSucceededInstances: 1
>     dockerImage: docker_image_0
>     resourcePerInstance:
>       gpu: 0
>       cpu: 4
>       memoryMB: 12288
>     commands:
>       - apt update
>       - apt install -y git
>       - 'git clone https://github.com/tensorflow/models'
>       - cd models/research/slim
>       - pip install --upgrade pip
>       - pip3 install contextlib2 Pillow tensorflow==1.14
>       - >-
>         python download_and_convert_data.py --dataset_name=cifar10
>         --dataset_dir=/tmp/data
>       - >-
>         python train_image_classifier.py --dataset_name=cifar10
>         --dataset_dir=/tmp/data --max_number_of_steps=1000 --clone_on_cpu=True
>     taskRetryCount: 0
> defaults:
>   virtualCluster: default

**Comment by abuccts** [comment] 2020-02-13 08:09
Hi, this issue is probably cased by your hardware, e.g. the cpu in your openstack cloud doesn't support AVX instructions. You can refer to [related TensorFlow issues](https://github.com/tensorflow/tensorflow/issues?utf8=%E2%9C%93&q=AVX+Illegal+instruction+%28core+dumped%29).

To confirm, simply change commands to:
```sh
pip3 install tensorflow==1.14
python -c "import tensorflow as tf"
```
You will get "Illegal instruction (core dumped)" as well. It would fail both in Docker or your VM host.
You could also check the log of `cat /proc/cpuinfo`.

Here're possible solutions:
* make your cloud/virtualization support AVX
* build tensorflow from source instead of installing by pip

**Comment by liuc-shaiic** [comment] 2020-02-14 03:19
Thanks abuccts! I make my cloud support AVX and the error is gone. But then another error occurs, I tried to add memory from 8GB to 64GB or change anther image(ufoym/deepo:tensorflow-py36-cpu) ,but the new error still exists, would you please take a look? Thx!
Here's the "View Exit Diagnostics" 
```
[Exit Trigger Info]

ExitTriggerMessage: FailedTaskCount 1 has reached MinFailedTaskCount 1 in TaskRole [Task_role_1]
ExitTriggerTaskRole: Task_role_1
ExitTriggerTaskIndex: 0
UserExitCode: 128

--------------------------------------------------------------------------------

[Exit Spec]

code: 255
phrase: CONTAINER_RUNTIME_UNKNOWN_FAILURE
issuer: PAI_RUNTIME
causer: UNKNOWN
type: UNKNOWN_FAILURE
stage: COMPLETING
behavior: UNKNOWN
reaction: RETRY_TO_MAX
reason: Container failed but the failure cannot be recognized by PAI Runtime
repro:
  - User program directly exits with exitcode 1
solution:
  - Check container log and find root cause
  - Wait result from next retry


--------------------------------------------------------------------------------

[Exit Diagnostics]

[2020-02-14 02:49:35.750]Exception from container-launch: 
ExitCodeException exitCode=255: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:998)
	at org.apache.hadoop.util.Shell.run(Shell.java:884)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1216)
	at org.apache.hadoop.yarn.server.nodemanager.DockerContainerExecutor.launchContainer(DockerContainerExecutor.java:312)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.launchContainer(ContainerLaunch.java:443)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:294)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:92)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-02-14 02:49:35.750]
[2020-02-14 02:49:35.751]Container exited with a non-zero exit code 255. Last 40960 bytes of runtime.pai.agg.error :
[PAI_RUNTIME_ERROR_START]
exitcode: 255
trigger: originalUserExitCode
reason: |
  User process exited with code: 128
solution: |
  
originalUserExitCode: 128
dockerStatus: 
caughtSignal: 
caughtException:
matchedUserLogString:
errorLogs:
  user: |
    
    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    
    
    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    
    debconf: unable to initialize frontend: Dialog
    debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
    debconf: falling back to frontend: Readline
    Cloning into 'models'...
    error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
    fatal: The remote end hung up unexpectedly
    fatal: early EOF
    fatal: index-pack failed
  runtime: |
    1581648575 ERROR REASON "User process exited with code: 128"
    WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
    1581648575 INFO USER_EXIT_CODE 128
  diskCleaner: |
[PAI_RUNTIME_ERROR_END]

[2020-02-14 02:49:35.752]
```
And here's the job config:
```
protocolVersion: 2
name: admin_1581644418489_93135352
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: openpai/tensorflow-py36-cpu
    name: docker_image_0
taskRoles:
  Task_role_1:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: 1
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 0
      cpu: 8
      memoryMB: 65536
    commands:
      - apt update
      - apt install -y git
      - 'git clone https://github.com/tensorflow/models'
      - cd models/research/slim
      - pip install --upgrade pip
      - pip3 install contextlib2 Pillow tensorflow==1.14
      - >-
        python download_and_convert_data.py --dataset_name=cifar10
        --dataset_dir=/tmp/data
      - >-
        python train_image_classifier.py --dataset_name=cifar10
        --dataset_dir=/tmp/data --max_number_of_steps=1000 --clone_on_cpu=True
    taskRetryCount: 0
defaults:
  virtualCluster: default
```

**Comment by abuccts** [comment] 2020-02-14 06:32
I still couldn't reproduce it. According to logs you pasted:
```
Cloning into 'models'...
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
It's a `git clone` issue, you should search `error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received` for that.

Maybe you used a http proxy or customized apt source, or there exists network issue in your cloud.

If retrying the job doesn't work, you could try the following ([reference](https://stackoverflow.com/questions/38378914/git-error-rpc-failed-curl-56-gnutls)):
```sh
apt install -y gnutls-bin
git config --global http.sslVerify false
git config --global http.postBuffer 1048576000
```
or find the root cause in your environment.

**Comment by liuc-shaiic** [comment] 2020-02-15 00:14
Hi Abuccts, it works! Thank you for helping me out! The following lines are the magic:
```
apt install -y gnutls-bin
git config --global http.sslVerify false
git config --global http.postBuffer 1048576000
```

**Comment by abuccts** [comment] 2020-02-15 09:18
@liuc-shaiic Glad it works. I will close this issue, pls feel free to reopen if you have additional questions.

**Closed by abuccts** 2020-02-15 09:18 UTC
