### ISSUE TITLE
WebPortal stucked 

### ISSUE THREAD

**Issue by sterowang** [Microsoft/pai#258] opened 2018-01-24 12:00 UTC
![image](https://user-images.githubusercontent.com/11206612/35331136-2d40831a-0141-11e8-80a7-90a97c5c324a.png)

**Comment by fanyangCS** [comment] 2018-01-24 12:33
I can't reproduce it. when will it happen? right after a job submission?

**Comment by fanyangCS** [comment] 2018-04-11 05:40
close the issue due to lack of sufficient info.

**Closed by fanyangCS** 2018-04-11 05:40 UTC
