### ISSUE TITLE
Every one can clone other's job, seems not safe

### ISSUE THREAD

**Issue by HaoLiuHust** [microsoft/pai#5770] opened 2022-04-30 13:52 UTC
**Organization Name**:

**Short summary about the issue/question**:
Every user can clone other's job , is it by design?

**Brief what process you are following**:

**How to reproduce it**:
in the job list, clone other user's job

**OpenPAI Environment**:
- OpenPAI version: v1.8.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by siaimes** [comment] 2022-05-02 09:36
I think it's by design, even if cloned, the job won't run properly because the private data is inaccessible.

**Comment by HaoLiuHust** [comment] 2022-05-10 01:53
> I think it's by design, even if cloned, the job won't run properly because the private data is inaccessible.

I guess they can access the data by mount nfs.. by the way, if every one can clone other's job, it's conflict with the markentplace private/public policy

**Comment by siaimes** [comment] 2022-05-14 01:26
> I guess they can access the data by mount nfs.

This is an inherent problem with NFS and doesn't seem to be fixed by pai.

> if every one can clone other's job, it's conflict with the markentplace private/public policy

You can only see which image and startup command was used in the job, it doesn't matter, the marketplace can also include documentation if you like.

**Comment by siaimes** [comment] 2022-05-14 09:24
https://github.com/microsoft/pai/issues/5522

**Closed** 2022-06-02 00:17 UTC
