### ISSUE TITLE
kill -9 $containerPid does not work 

### ISSUE THREAD

**Issue by weiranzhixin** [Microsoft/pai#1611] opened 2018-10-29 02:56 UTC
in rest-server/src/templates/yarnContainerScript.mustache 
`pid=$(docker inspect --format={{{ inspectFormat }}} $docker_name) && kill -9 $pid `
 * when  the related job was already stopped, container still exist 
* command:`kill -9 $pid` was confirmed to be excuted already , container still exist
* docker version: 18.06.1-ce

**Comment by mzmssg** [comment] 2018-10-29 03:01
which version pai for this issue?

**Comment by weiranzhixin** [comment] 2018-10-29 03:14
v0.7.1

**Comment by mzmssg** [comment] 2018-10-29 03:36
Need more information to locate the issue:

> when the related job was already stopped, container still exist

These job is stopped in webportal or finish by itself?

> command:kill -9 $pid was confirmed to be excuted already , container still exist

Could you give more details on how to confirm.

Besides, could you help check the container status? Could `docker logs` and `docker exec` work for this container. If answer is no, I think it's a docker issue, otherwise it should be our bug, please help provide `DockerContainerDebug.log` and `YarnContainerDebug.log` to solve it.

**Comment by weiranzhixin** [comment] 2018-10-29 03:58
* the status of the job is `stopped` shown in webportal
* YarnContainer log shows `kill -9 pid` was executed
* docker logs and docker exec  does not work for this containter now ...
have you ever met similar problem, or do you some advice for this problem ?

**Comment by mzmssg** [comment] 2018-10-29 05:46
It seems docker daemon enter some weird zombie status. We are not sure whether our code logic trigger it. But restarting dockerd should solve it.

We are also finding the cause now. In our latest code, we have refactored scripts to avoid force kill like `kill -9` or `docker kill`,  which might help to solve this problem.

If you find a stable reproducing job, welcome report to us.

**Comment by fanyangCS** [comment] 2018-10-29 06:47
@weiranzhixin  this PR https://github.com/Microsoft/pai/pull/1435 addressed the issue. Note that we are in the middle of code refactoring so as to make the code more robust.

**Comment by mzmssg** [comment] 2018-10-29 07:02
@weiranzhixin Another commit is #1461

**Comment by fanyangCS** [comment] 2018-11-21 10:01
close this issue as it is solved.

**Closed by fanyangCS** 2018-11-21 10:01 UTC
