### ISSUE TITLE
Job details returns 304 after the first time retrial.

### ISSUE THREAD

**Issue by sterowang** [Microsoft/pai#468] opened 2018-04-12 06:19 UTC
Job details URL such as http://10.151.40.179/rest-server/api/v1/jobs/cntk-test-26592-24686 always returns 304 after the first time retrial. Rest APIs should always refreshed in theory.

**Comment by jingruhou** [comment] 2018-06-05 15:08
how to solve the question：‘returns 304’ ?

**Comment by ydye** [comment] 2018-06-06 02:07
@fanyangCS

**Comment by fanyangCS** [comment] 2018-08-21 12:13
@sterowang , can you reproduce this issue?

**Comment by fanyangCS** [comment] 2018-10-16 10:49
@Gerhut , I believe you have fixed this issue. please confirm.

**Comment by Gerhut** [comment] 2018-10-19 10:30
Etag is enabled in REST Server to save traffic. It means that if there is a version of response body in browser cache, and the hash matches the one server generated from the fresh response body, a 304 will respond as a substitute of full response body. So it does not mean that REST server does not refresh data from the upstream server, just a hash-match between browser cache and fresh response.

However there is also a risk. When response replacement in pylon is changed, since pylon does not clear or re-calculate the etag, browser cannot invalidate their cache if REST server does not get some changes. Disable etag generation in REST server may be better, and will enable in pylon if really needed.

**Comment by Gerhut** [comment] 2018-10-23 07:01
After offline discussion, I plan to add a etag transformer in pylon to resolve the config replacement issue.

The etag in REST server is reserved and will be transformed in pylon by appending a version field.

After investigating, it could be implemented by nginx's map module.

Here is a [demo](https://github.com/Gerhut/nginx-alter-etag).

**Comment by Gerhut** [comment] 2019-03-18 06:22
Fixed in #1636

**Closed by Gerhut** 2019-03-18 06:22 UTC
Labels: enhancement, restserver
