### ISSUE TITLE
All launcher-test in the platform is Failed. 

### ISSUE THREAD

**Issue by JianfeiHu** [Microsoft/pai#1332] opened 2018-09-11 05:51 UTC
The platform failed all launcher-test from 8:56 p.m. on September 10, 2018 to 8:33 a.m. on September 11, 2018, without allocating resources and container creation. Jobs submitted by other users were running normally, and the platform returned to normal later.

**Comment by fanyangCS** [comment] 2018-09-11 07:46
can you find out the root cause? like which component restarts

**Comment by xudifsd** [comment] 2018-09-11 08:40
I see you're deployed v0.6.1, on what git branch did you boot up and started all service?

**Comment by xudifsd** [comment] 2018-09-11 08:44
One of [application summary](http://10.150.144.225/view.html?jobName=launcher-test-24247-32652) says `AM lost after RMResynced`. Maybe this is due to resource manager?
@yqwang-ms please take a look.

**Comment by yqwang-ms** [comment] 2018-09-11 09:41
It means Launcher has submitted the app to YARN RM, but afterwards cannot find it in YARN RM. So, please check RM.

**Comment by mzmssg** [comment] 2018-09-11 10:38
I check the yarn application list, but can't find these failed app during that time.
![image](https://user-images.githubusercontent.com/11887940/45354996-bef0d480-b5f1-11e8-9078-b303dbef6647.png)

**Comment by mzmssg** [comment] 2018-09-11 10:55
And I try to search RM log, but we don't fix redundant port output in 2.7.2, the info has been flushed.
![image](https://user-images.githubusercontent.com/11887940/45355899-40e1fd00-b5f4-11e8-9405-8f012eef23c7.png)

**Comment by fanyangCS** [comment] 2018-10-16 11:28
no further action. close the issue.

**Closed by fanyangCS** 2018-10-16 11:28 UTC
