### ISSUE TITLE
nodes "10.0.1.6" not found

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1194] opened 2018-08-29 06:01 UTC
It's not the first time, the cluster install encountered too. ("10.0.1.8" not found).
http://40.76.53.138:33080/blue/organizations/jenkins/pai/detail/PR-1192/3/pipeline

2018-08-29 05:57:05,601 [INFO] - paiLibrary.paiService.service_start : Begin to execute service zookeeper's start script.
Error from server (NotFound): nodes "10.0.1.6" not found
2018-08-29 05:57:05,699 [ERROR] - paiLibrary.common.linux_shell : Failed to execute the start script of service zookeeper

**Comment by YanjieGao** [comment] 2018-08-30 01:28
seems k8s or kubectl can't aware this node?

**Comment by fanyangCS** [comment] 2018-09-20 08:38
could not reproduce. looks like a race condition. may have been resolved by recent deployment fixes. close for now.

**Closed by fanyangCS** 2018-09-20 08:38 UTC
Labels: deployment
